### ISSUE TITLE
requires Http by default

### ISSUE THREAD

**Issue by twop** [ng2-ui/ng2-auto-complete#102]
Decided to try it out and after copy/pasting the example ({id, value}) got this:
No provider for Http!

Checked the code. It seems that utility class Ng2AutoComplete can have it as @Optional()
see: https://angular.io/docs/ts/latest/guide/dependency-injection.html

**Comment by allenhwkim** [comment]
Hmm, I have always thought `Http` is a necessary part of auto complete. 
I would appreciate if you make a PR.
