### ISSUE TITLE
connect with WebPack

### ISSUE THREAD

**Issue by khex** [ng2-ui/ng2-auto-complete#103]
I'm playing with [universal-starter](https://github.com/angular/universal-starter) that builds by WebPack

How to
> add map and packages to your systemjs.config.js

to `webpack.config.js` to avoid this error

`var paramTypes = ctorParameters.map(function (ctorParam) { return ctorParam && ctorParam.type; });` 
`ctorParameters.map is not a function`

**Comment by allenhwkim** [comment]
If you use webpack, you don't need to set `systemjs.config.js` at all.

**Comment by AbdullahNasir** [comment]
getting the same error

**Comment by allenhwkim** [comment]
Did you update your angualr version?
https://stackoverflow.com/questions/41285889/ctorparameters-map-is-not-a-function-in-angular2-mdl

**Comment by AbdullahNasir** [comment]
yeah, trying that
