### ISSUE TITLE
cursor focus

### ISSUE THREAD

**Issue by crh225** [ng2-ui/ng2-auto-complete#106]
When I click on the auto complete box, the cursor focus does not show the normal |

instead it is blank, and it is confusing to the user what textbox the user is in. For example, we have 20 autocomplete boxes on a form.
```
<input auto-complete 
  class="form-control"
  [(ngModel)]="selectedColumn" 
  [source]="columnsNotInDv" 
  [min-chars]="1" 
  [max-num-list]="10"
  placeholder="enter column name"
  display-property-name="DisplayName">
```

**Comment by allenhwkim** [comment]
![image](https://cloud.githubusercontent.com/assets/1437734/22031357/5e50b99c-dcae-11e6-88b9-e2dbd1844cab.png)

I see a cursor. Is it environmental issue?

**Comment by crh225** [comment]
@allenhwkim , I am testing in the latest version of google chrome. May I ask, what browser are you using? I will test in IE as well.

**Comment by allenhwkim** [comment]
![image](https://cloud.githubusercontent.com/assets/1437734/22036477/b789ec8c-dcc1-11e6-894b-f7f956355598.png)

**Comment by crh225** [comment]
It must be something wrong with my css somewhere. cheers.

**Comment by Gahen** [comment]
for future reference: removing the `form-control` class fixes
