### ISSUE TITLE
styling needed

### ISSUE THREAD

**Issue by weinianhe** [ng2-ui/ng2-auto-complete#108]
Hi is there styling functionality available for this project? let me know thanks!

**Comment by allenhwkim** [comment]
No, but it's possible.
You can override default style from your end unless you want to improve the default style.
https://github.com/ng2-ui/ng2-auto-complete/blob/master/src/ng2-auto-complete.component.ts#L54

**Comment by allenhwkim** [comment]
If you want to imporove the existing style, please create another PR
