### ISSUE TITLE
Error converting circular structure to JSON

### ISSUE THREAD

**Issue by crh225** [ng2-ui/ng2-auto-complete#110]
Here is my plunkr
http://plnkr.co/edit/CaLlgu1NhwCTH88kO56S?p=preview

my columns (my list im trying to bind to) look like this
```
    [
  {
    "name": "item 1",
    "guid": "C2BEADE9-95A8-421A-B3C0-EC50CCD5556D"
  },
  {
    "name": "item 2",
    "guid": "A2A57D18-EB15-4D59-8148-824231AC5069"
  }
]
```

![image](https://cloud.githubusercontent.com/assets/19475195/22212813/a81f5698-e157-11e6-9f31-b40027e8779c.png)

**Comment by allenhwkim** [comment]
Thanks for reporting, but it's not related to this module.
