### ISSUE TITLE
Working with Observables of custom services

### ISSUE THREAD

**Issue by Jonatthu** [ng2-ui/ng2-auto-complete#111]
The next code is not working for me :/
Am I forgetting something?

`Error in ./Ng2AutoCompleteComponent class Ng2AutoCompleteComponent - inline template:4:4 caused by: Cannot read property 'GetbyCategoryName' of undefined`

Method
`  public searchRegularCategories(term: string) {
    return this._categoriesService.GetbyCategoryName(term).map(x => x.data);
  }`
Html
`            <input
             ng2-auto-complete
             [list-formatter]="myListFormatter"
             [source]="searchRegularCategories"
             type="text"
             display-property-name="description"
             accept-user-input="false"
             placeholder="Write the category name" #category>`

Service
`    public GetbyCategoryName(name: string ): Observable<RG<ListingCategory[]>> {
        return this._http.get(`http://localhost:53903/api/v1/categories/regular?name=${name}`, { headers: this.headers })
            .map((resp: Response) => resp.json())
            .catch((error: any) => {
                return Observable.throw(error);
            });
    }`

**Comment by Jonatthu** [comment]
Seems like only accept a property function as parameter and not a method, is there a real reason for why ?

But with this is working perfectly!
```

  public searchRegularCategories = (term: string) => {
    return this._categoriesService.GetbyCategoryName(term).map(x => x.data);
  }
```

**Comment by allenhwkim** [comment]
it's about execution context. I am not sure why it must be assigned as a variable.

@ndcunningham can you investigate that if it is possible to assign a method instead of a variable for this. 

Related source code: https://github.com/ng2-ui/ng2-auto-complete/blob/master/src/ng2-auto-complete.component.ts#L212

**Comment by ndcunningham** [comment]
maybe just do `.bind(this)` for your bound callback?

**Comment by Jonatthu** [comment]
You mean on the HTML or the method?

[source]="foo.bind(this)"?

**Comment by allenhwkim** [comment]
@Jonatthu yes he meant for that I think. Does it work for you?

**Comment by allenhwkim** [comment]
@Jonatthu xxxxx.bind(this) works, and an example is updated.
  http://plnkr.co/edit/uY3rsBg9F8aaoemP4Mjp?p=preview&open=app%2Fapp.component.ts

**Comment by Jonatthu** [comment]
Thank you very much, It is working !
