### ISSUE TITLE
blur not working as expected

### ISSUE THREAD

**Issue by crh225** [ng2-ui/ng2-auto-complete#112]
http://plnkr.co/edit/iIWNEkuvs61hk5blXS5X?p=preview

blur is getting called when the element is focused

```
      <input [ngModel]="model1"
      (blur)='callAlert()'/>
```

after clicking out of the textbox, it does not re call blur either.

**Comment by allenhwkim** [comment]
This is intentional design to have a separate input for autocomplete.
Let me find out any way not to use separate input. It make take some time

**Comment by crh225** [comment]
maybe when the model changes, call blur?

**Comment by allenhwkim** [comment]
@ndcunningham Can you improve this not to use input tag when it's called by a directive?

1. Keep component input tag as it is
2. When it is called by a directive, communicate to component directly without using input field of the component. 

The following behaviour should be set for the input field. 
https://github.com/ng2-ui/ng2-auto-complete/blob/master/src/ng2-auto-complete.component.ts#L25-L31

   *  (focus)="showDropdownList()"
   *  (blur)="hideDropdownList()"
   *  (keydown)="inputElKeyHandler($event)"
   *  (input)="reloadListInDelay()"

Ping me if you can try. If not, I will start digging into it.

**Comment by crh225** [comment]
Done!
