### ISSUE TITLE
min-chars=1 then backspace, shows empty div w/ grey background

### ISSUE THREAD

**Issue by crh225** [ng2-ui/ng2-auto-complete#118]
see #97 

repeat the steps, and you can see a little grey div that appears, but it is empty.
http://plnkr.co/edit/dOEp33aYHNyDz0jg8tCq?p=preview

![image](https://cloud.githubusercontent.com/assets/19475195/22308704/acc376d6-e30d-11e6-9a12-f286cfb6a664.png)

**Comment by crh225** [comment]
@allenhwkim , have you already pushed to NPM?

**Comment by allenhwkim** [comment]
@crh225 I did, the recent version is 0.10.0

**Comment by crh225** [comment]
cool. Ill get latest.
