### ISSUE TITLE
Accept-user-input=false does not revert value

### ISSUE THREAD

**Issue by johnrayner** [ng2-ui/ng2-auto-complete#119]
I have set accept-user-info="false" in [this plunk](http://plnkr.co/edit/ypgiDM3jtmm1za31Qkk8?p=info).  I'd like to have the value on the input box revert if the user does not pick an option from the list, e.g. if the user type "q" on the plunk and tabs out, then the input box and model should revert to undefined.  Is this possible with the current version?

**Comment by crh225** [comment]
@johnrayner, you need to put it in square brackets

 [accept-user-info]="false"

http://plnkr.co/edit/soSvjHNUeNov8S2HSrfH?p=preview

**Comment by crh225** [comment]
if you don't false gets evaluated as a string, and angular doesnt evaluate it as a boolean

**Comment by crh225** [comment]
same thing if you ever decide to use list-formatter="myListFormatter"

it would need to say [list-formatter]="myListFormatter"

**Comment by johnrayner** [comment]
Doh!  Thanks for the help.  Works nicely now.
