### ISSUE TITLE
Prevent memory leaks by unsubscribing to variables, ngOnDestroy

### ISSUE THREAD

**Issue by fungjj92** [ng2-ui/ng2-auto-complete#12]
We subscribe to component.valueSelected in auto-complete-directive.ts for example. I think the best practice is to also implement ngOnDestroy and .unsubscribe from observables there.

**Comment by allenhwkim** [comment]
Yes, exactly. Thanks for the feedback. I will implement it soon. You can also send me a PR if you are in a hurry.

**Comment by allenhwkim** [comment]
This has been updated with version 0.5.3. Please test.

**Comment by fungjj92** [comment]
Looks good on this project. I had trouble pulling in the changes into my own project, however.

**Comment by allenhwkim** [comment]
Closing, let me know if not fixed.
