### ISSUE TITLE
question: searching scans entire model

### ISSUE THREAD

**Issue by crh225** [ng2-ui/ng2-auto-complete#121]
When searching for "t1" on this plunkr:
http://plnkr.co/edit/2agivY9m6eOxudJxHmeh?p=preview

all results return. Is there a way we can just get it to search certain fields, such as key/value fields only?

**Comment by crh225** [comment]
In my use case, most of my models have a true/false value in the model. if they search for the word true, even though it is not a key/value field, all results show.

**Comment by allenhwkim** [comment]
You need to build a Observer function for that. Please take a look at 'Observer Source' example for tha.
