### ISSUE TITLE
Bug: accept-user-input not working

### ISSUE THREAD

**Issue by shyamal890** [ng2-ui/ng2-auto-complete#122]
I don't know if I am doing something wrong but when I use `accept-user-input = 'false'` in the [example of Key/Name,](http://plnkr.co/edit/3pB1Gx?p=preview) putting a non existing name in input results in model being update to the user entered value. It should have been reverted back to previously selected model.

**Comment by allenhwkim** [comment]
http://plnkr.co/edit/T5K1faYzb0LeSD9IttxE&open=app/app.component.ts

The default value of `accept-user-input` is false,
If you want to prevent user entering invalid value use `[accept-user-input]="true"`

**Comment by shyamal890** [comment]
@allenhwkim Not able to see any difference
![check](https://cloud.githubusercontent.com/assets/6606965/22625139/048859f0-ebb4-11e6-908d-cbd44b852ee4.gif)

**Comment by allenhwkim** [comment]
`accept-user-input` is deprecated for simplicity

As in README.md

<strike>**accept-user-input** boolean, if false and does not match to source given, it goes back to the original value selected.,</strike> 

please use readonly="readonly" to force user to select only from list.

**Comment by olek-d** [comment]
but readonly="readonly" doesn't allow you to type anything in input to filter values from the list. accept-user-input was very useful :(
