### ISSUE TITLE
bug: autcomplete does not allow the character [

### ISSUE THREAD

**Issue by crh225** [ng2-ui/ng2-auto-complete#124]
Go to plunkr
http://plnkr.co/edit/3pB1Gx?p=preview

in first input click into it and hit the character "["

![image](https://cloud.githubusercontent.com/assets/19475195/22515946/e18953ca-e869-11e6-9256-c6ea89c293ea.png)

![image](https://cloud.githubusercontent.com/assets/19475195/22515987/0387c51a-e86a-11e6-8bcb-8181f6732da2.png)

**Comment by crh225** [comment]
doesnt like slash either

![image](https://cloud.githubusercontent.com/assets/19475195/22523870/89dd94e8-e886-11e6-8917-3883e54cdb2a.png)

![image](https://cloud.githubusercontent.com/assets/19475195/22523876/8f6c2a00-e886-11e6-985a-7627e562c275.png)

**Comment by crh225** [comment]
different plunkr
http://plnkr.co/edit/2XRrck2cWVWcvbJnj6z5?p=preview

![image](https://cloud.githubusercontent.com/assets/19475195/22524369/88db1780-e888-11e6-8968-6d5b7031de07.png)

![image](https://cloud.githubusercontent.com/assets/19475195/22524371/8ef9f884-e888-11e6-823e-d57223dec0de.png)

**Comment by allenhwkim** [comment]
Fixed and released 0.10.2

**Comment by crh225** [comment]
verified
