### ISSUE TITLE
Feature Request - Show Full List When Box is Clicked

### ISSUE THREAD

**Issue by crh225** [ng2-ui/ng2-auto-complete#125]
It would be really useful to show all values when the input box is clicked. I realize this is an autocomplete component, but it can also double as a useful dropdown component.

**Comment by allenhwkim** [comment]
I think this feature is already there

**Comment by allenhwkim** [comment]
https://rawgit.com/ng2-ui/ng2-auto-complete/master/app/index.html#/component-test

**Comment by crh225** [comment]
I will clarify tomorrow what I'm talking about with an example

**Comment by crh225** [comment]
When you focus in a texbox, it shows only one item in the list.
![image](https://cloud.githubusercontent.com/assets/19475195/22552777/e9a9ac92-e91f-11e6-9de6-6911277ce3a3.png)

What Im proposing is that when you focus on the textbox, it show all items, even if a value is already selected. What we want to do is use the list-formatter to highlight items that match, and show all values all the time.
![image](https://cloud.githubusercontent.com/assets/19475195/22552829/20d81320-e920-11e6-99fe-01ca485ffc14.png)

**Comment by crh225** [comment]
the end result would look like this
![image](https://cloud.githubusercontent.com/assets/19475195/22552911/6ba03f04-e920-11e6-98e0-418770656154.png)

**Comment by allenhwkim** [comment]
Gee

**Comment by allenhwkim** [comment]
Sorry auto correction
Yes exactly that feature is already there by separating directive and component

**Comment by crh225** [comment]
Ill try it, but the demo you provided does not show all items, after the initial item is selected.

**Comment by allenhwkim** [comment]
Ok I will give you a different example

**Comment by crh225** [comment]
here is my plunkr so far:
http://plnkr.co/edit/mTvPCm84Po7eDc0PMpWJ?p=preview

**Comment by allenhwkim** [comment]
Try take a look at this example, http://plnkr.co/edit/FBIe69?p=preview
If this is too difficult, we can improve.

```
@Component({
  selector: "my-app",
  template: `
    <input [(ngModel)]="myModel"
           (focus)="show()"
           (blur)="hide()" />
    <ng2-auto-complete
      (valueSelected)="myModel = $event"
      [show-input-tag]="false"
      [source]="[1,2,3,4,5]"
    ></ng2-auto-complete>
 `
})
export class AppComponent {
  @ViewChild(Ng2AutoCompleteComponent) ng2AutoComplete: Ng2AutoCompleteComponent;
  show() {
    this.ng2AutoComplete.showDropdownList({target:{value:''}});
  }
  hide() {
    this.ng2AutoComplete.hideDropdownList();
  }
}
```

**Comment by crh225** [comment]
This is the functionality! Thanks

I did notice something though:
![image](https://cloud.githubusercontent.com/assets/19475195/22557117/13fc45d6-e92f-11e6-8528-8580814737c6.png)


I can mess around with the list formatter and see what I can do, but shouldnt the selected item be highlighted, and not the first item in the list?

**Comment by crh225** [comment]
![image](https://cloud.githubusercontent.com/assets/19475195/22557204/6c6628cc-e92f-11e6-9d31-0599073d0e01.png)

another exapmle

**Comment by crh225** [comment]
your suggested improvement would make it easier to use. it saves an import statement and 8 lines of code.

**Comment by shyamal890** [comment]
Hmm, there should be an easier way to achieve this. Something like `minLength` when set to 0 would dropdown options on focus.

**Comment by allenhwkim** [comment]
![image](https://cloud.githubusercontent.com/assets/1437734/22767868/4b9fdba2-ee4c-11e6-8723-e15fd1e05ac6.png)

![image](https://cloud.githubusercontent.com/assets/1437734/22767876/59932c5a-ee4c-11e6-817d-1b4c2f6dd82b.png)
