### ISSUE TITLE
User can bypass autocomplete input box when using Material design

### ISSUE THREAD

**Issue by johnrayner** [ng2-ui/ng2-auto-complete#128]
We use material design with accept-user-input set to false.  What we've noticed is that when users click on the field label to apply focus, the material input box gets focus rather than the auto complete input box.

**Current behavior**
Plunker: http://plnkr.co/edit/UbGH3h
* Enter a value using auto complete behavior
* Click on the "amount" label
* Focus is now applied to the material input box
* Key in an invalid value and tab out of the field - invalid value remains

**Expected/desired behavior**
* Auto complete behavior should be triggered and the invalid value should be reverted

**Other information**
The material CSS class "md-input-wrapper" applies 16px of top-margin and bottom-margin.  It is this space which is routing the click event to the material input control.

**Comment by allenhwkim** [comment]
This happens `(focus)`, `(blur)` applies to `<md-input>`, not to `<input>`

https://github.com/ng2-ui/ng2-auto-complete/blob/master/src/ng2-auto-complete.directive.ts#L22

@ndcunningham Do you want to fix this?

**Comment by johnrayner** [comment]
Thanks for the code change.  This seems to fix the focus issue, i.e. focus now always goes to the auto-complete input element.  However, the control doesn't revert its value on blur.  It's accepting user input of invalid values.
