### ISSUE TITLE
logging

### ISSUE THREAD

**Issue by crh225** [ng2-ui/ng2-auto-complete#129]
can you please turn off logging or make it optional and default to false?

![image](https://cloud.githubusercontent.com/assets/19475195/22560478/65395802-e93a-11e6-86e7-9fd0d25d6319.png)

**Comment by crh225** [comment]
![image](https://cloud.githubusercontent.com/assets/19475195/22562745/74a9bc88-e943-11e6-93be-5288ee35b17e.png)

**Comment by crh225** [comment]
Im using version 0.10.2

**Comment by ndcunningham** [comment]
I removed it with https://github.com/ng2-ui/ng2-auto-complete/commit/cd777b2f6f135b71a53d3e4510d332ca2433e4ec oh well
