### ISSUE TITLE
How to set the default value of the selection using FormControl or FormGroup?

### ISSUE THREAD

**Issue by aslamj** [ng2-ui/ng2-auto-complete#130]
How to set a selected value from model, when a FormControl or FormGroup is used for the reactive forms? 
I know that when ngModel is used, then the selection from the model works fine (http://plnkr.co/edit/3pB1Gx?p=preview), 

but it is not working in reactive forms (http://plnkr.co/edit/QH6LiZvkscNcYiGubZGl?p=preview).

**Current behavior**
[object Object] is being displayed as current selection and valueChanged method is not called.

**Expected/desired behavior**
the value specified by display-property-name should be displayed and the valueChanged method is must be called (at-least once in the beginning).

**Comment by allenhwkim** [comment]
This directive does not do anything related to the INITIAL value. It just display as it is. Shouldn't it?

**Comment by aslamj** [comment]
Should it display the item value as specified by 'display-property-name' for the initial value as compared to displaying what ever is being returned from FormControl.vaule toString() method. It works fine with the ngModel way, meaning it is honoring the  'display-property-name' for the initial value being set from the ngModel.

**Comment by allenhwkim** [comment]
@aslamj you are right
It does only set the value properly only for `ngModel`
https://github.com/ng2-ui/ng2-auto-complete/blob/master/src/ng2-auto-complete.directive.ts#L78

@ndcunningham can you take a look at this?

**Comment by aslamj** [comment]
Right now I'm using following:
```
            [(ngModel)]="_form.controls['xxxxx'].value"
            [ngModelOptions]="{standalone: true}"
```
for the use case to work with the initial values, but wish it could be fixed for forControl/forControlName.

**Comment by aslamj** [comment]
The fix #131 broke the use case where: model->view binding is needed, but my initial value is null or undefined (sometimes), see plunker: http://plnkr.co/edit/YhF5dRE8G7MD30rGilY7?p=preview

TypeError: Cannot read property 'name' of null
    at Ng2AutoCompleteDirective.ngOnInit (VM1251 ng2-auto-complete.umd.js:632)
    at Wrapper_Ng2AutoCompleteDirective.ngDoCheck (VM1315 wrapper.ngfactory.js:177)

**Comment by allenhwkim** [comment]
published again as 0.10.5.

**Comment by sandrose48** [comment]
this issue still exist .... its not fixed yet?

**Comment by julianarana** [comment]
The problem is solved if a toString method on the source objects. It might return the desired value to be shown to the user... 
{
id: 'anyId',
name: 'name'
toString: function(){return this.name}
}

Hope this issue is solved soon

**Comment by jamsheedpk** [comment]
thanks **julianarana**
is working  is solved 
My code 
**html** 

```
<div class='col-sm-6'>
                        <div class='form-group'>
                          <label><b>Member type:</b></label>
                          <input  ng2-auto-complete
                                  formControlName="cmbMemberType"
                                  [source]="objMemberTypeData"
                                  [list-formatter]="autocompleMemberType"
                                  value-property-name="_id"
                                  display-property-name="strMemberTypeName"
                                  placeholder="Select member type"
                                  class="form-control">
                          <div class="alert" *ngIf="!frmUserAddStepOne.controls['cmbMemberType'].valid && frmUserAddStepOne.controls['cmbMemberType'].touched">Member type  is required</div>
                        </div>
                      </div>
```

**Type script**

 public objMemberTypeData: object;  /// fill object data 

### autocompleMemberType function is  

```
autocompleMemberType = (data: any): SafeHtml => {
    let html = `<span>${data.strMemberTypeName}</span>`;
    return this.sanitizer.bypassSecurityTrustHtml(html);
  }
```
//Set The default value 
this.Form.patchValue({cmbMemberType: {strMemberTypeName:"JAMSHEED",_id:123}});
