### ISSUE TITLE
Feature Request: Debounce property

### ISSUE THREAD

**Issue by shyamal890** [ng2-ui/ng2-auto-complete#134]
If a http call is to be made to the server everytime on change in searchText, it would be pertinent to have debounce in place

**Comment by allenhwkim** [comment]
There is 500ms delay already implemented

**Comment by allenhwkim** [comment]
Is there an issue with debounce problem?

**Comment by allenhwkim** [comment]
Closing this by not following issue template. Please re-create this issue.
