### ISSUE TITLE
Feature Request: value property should bind with ngModel

### ISSUE THREAD

**Issue by shyamal890** [ng2-ui/ng2-auto-complete#135]
It seems that `value property name` is not binding with `ngModel` rather the whole model is binded. 

This feature would be very useful for:
1. when we only want to retrieve a property from a model but not the whole model.
2. Default binding on initialization.

[Example Plunker](http://plnkr.co/edit/ZCvxVc6mKTz5OEM3M2IP?p=preview) in which by `value-property` is set to `id`. However, setting `ngModel` to a default `id` doesn't work.

**Comment by allenhwkim** [comment]
Closing this by not following issue template. Please re-create this issue.
