### ISSUE TITLE
Feature Request: value property should bind with ngModel

### ISSUE THREAD

**Issue by shyamal890** [ng2-ui/ng2-auto-complete#136]
**Current behavior**
It seems that `value-property-name` is not binding with `ngModel` rather the whole model is binded.

**Expected/desired behavior**

When defining `value-property-name` one would only want to retrieve a property from a model but not the whole model. May be `value-property-name` should be changed to `track-by-property` and `value-property-name` would define if the whole model or a property value binds with `ngModel`

**Usecase**
Proper binding on initialization from property value instead of whole model.
[Example Plunker](http://plnkr.co/edit/ZCvxVc6mKTz5OEM3M2IP?p=preview) in which by `value-property-name` is set to id. Setting ngModel to a default `id` should work.

**Comment by allenhwkim** [comment]
I am not sure about this requirement. From my experience, almost all time, I wanted to have the full object instead of only value,  e.g. Product, Item, or Page, instead of product name, item name and page name.

**Comment by shyamal890** [comment]
Let me give an example where this is required:
Lets say there are some hotel rooms whose model would contain properties: `RoomId, Type, Cost, Capacity, isAlloted`
`User Model` contains properties: `UserId, Email, Age, Name`

App may have already downloaded a list of users earlier. 
Through auto complete we want to assign a predefined user to a room. On selection I only need to send `UserId` with `RoomId` and not whole `User model`.

Moreover, `ui-select`, `angular-ui` too supports this feature for angular 1.

**Comment by allenhwkim** [comment]
What if I need a whole model as a value?

e.g. {id: 1, name: "My Name", address: "xxx", ...}

display-property-name: `name`

What if I need whole model, not only id, as the value?

**Comment by shyamal890** [comment]
> May be value-property-name should be changed to track-by-property and value-property-name would define if the whole model or a property value binds with ngModel

**Comment by allenhwkim** [comment]
Not fully following,. can you give me an example with this ` {id: 1, name: "My Name", address: "xxx", ...}`

**Comment by shyamal890** [comment]
When `value-property-name = "id"` the whole model is binded. 

However, to chose only one property of the model to bind. This is what I propose:
1. Changing only attribute name of `value-property-name` to `track-by-property` and leaving it's implementation intact.
2. Create a new attribute `value-property-name`.

As per point 2, the implementation is changed in such a way that if a user wants to get only `name` from `{id: 1, name: "My Name", address: "xxx", ...}`. 
He will set:
     `value-property-name = "name"`, `track-by-property = "id"`, `display-property-name = "name"` 

If the user wants to get the whole model:
     `track-by-property = "id"`, `display-property-name = "name"`

**Comment by shyamal890** [comment]
Absolutely, that is why the current implementation of `value-property-name` remains as it is just under a different name `track-by-property`. Hope I am making sense here.

**Comment by allenhwkim** [comment]
What if user does not specify `track-by-property`, should it be `id` in default?

**Comment by allenhwkim** [comment]
NOTE:From the code, `valuePropertyName` is not much in use

**Comment by shyamal890** [comment]
Yes if user doesn't specific `track-by-property` it will take `id` as `default`. Incase of an array of say string (single property) there is no need for `track-by-property`, `value-property-name` and `display-property-name`

**Comment by shyamal890** [comment]
> NOTE:From the code, valuePropertyName is not much in use

Agreed, it can be even argued that it should be removed altogether.

**Comment by allenhwkim** [comment]
@svitlychnyi 
How about this?

*  introducting `select-value-of` instead of `track-by-**`.
  * because we are not tracking any. 
  * If omitted, select the whole model, the element of list
  * If given, return the key of the row as the value

* `display-property-name` and `value-property-name`
   * It is only used for default list formatting.
   * We can rename it or
      * list-value-property-name
      * list-display-property-name
  * Or, remove both, and introuce simple list formatter
     * e.g. `list-formatter="(id) name"`

**Comment by shyamal890** [comment]
> Introducing select-value-of instead of track-by-**.
 Perfect! Would be great to have this in place.

**Comment by shyamal890** [comment]
Any timeline on when this feature would be implemented?
