### ISSUE TITLE
valdiate user input to force user choose one of suggested elements

### ISSUE THREAD

**Issue by youneschaoui** [ng2-ui/ng2-auto-complete#137]
Is there a native way to validate input to make sure if user wont give free text other than values suggested ?

**Comment by allenhwkim** [comment]
README.md says
```
**accept-user-input** boolean, if false and does not match to source given, it goes back to the original value selected.
```
This does not work?

**Comment by youneschaoui** [comment]
it's not secure to switch value without notifying the user, a better way to handle this is to validate input and show error message

**Comment by allenhwkim** [comment]
@youneschaoui please guide me. I do not have a plan to show a popup message showing an error.

**Comment by allenhwkim** [comment]
How about setting `readonly="true"`, so that user cannot modify its value?

**Comment by allenhwkim** [comment]
I have tested with `readonly="true"`, and it works fine. closing.
