### ISSUE TITLE
Feature Request: display-property-name 

### ISSUE THREAD

**Issue by Jonatthu** [ng2-ui/ng2-auto-complete#140]
I want to display after selected the full name of a client, but it has different properties like this

`display-property-name="firstName + '' + middleName + 'lastName'"`

This is not working of course but Can I do something like this?
This can be useful for other situations with other objects

**Comment by allenhwkim** [comment]
Please use `list-formatter` for custom formatting.
Closing because of not following issue template.

**Comment by Jonatthu** [comment]
@allenhwkim this is for the list, what I want is for the input value for display the value selected

**Comment by youneschaoui** [comment]
Same probleme here

**Comment by francoberton** [comment]
I've same problem of Jonatthu! Any solution?
