### ISSUE TITLE
drop down shows "undefined" in example three of sample plunker 

### ISSUE THREAD

**Issue by benwu9999** [ng2-ui/ng2-auto-complete#141]
example three "With Array of Key/Name" in the sample plunker: http://plnkr.co/edit/3pB1Gx?p=preview

when one click on the text box or start typing, the matched result shows "(undefined) undefined".  I have seen the same when the "display-property-name" and/or "value-property-name" are set to non-default value, i.e "display-property-name" set to string other than "value" and "value-property-name" set to string other than "id".

**Comment by allenhwkim** [comment]
It's fixed with new `list-formatter`
