### ISSUE TITLE
Upgrade webpack version from 1.* to 2.*

### ISSUE THREAD

**Issue by allenhwkim** [ng2-ui/ng2-auto-complete#142]
Webpack version 2 has very significant changes, and configuration is not backward compatible 
https://blog.madewithenvy.com/getting-started-with-webpack-2-ed2b86c68783#.3tv0tylgk

We need to upgrade to webpack 2.* and rebuild our webpack.config.js

**Comment by allenhwkim** [comment]
@ndcunningham Can you take care of this?

**Comment by allenhwkim** [comment]
Please take a look at ng2-map, which has already upgrade to webpack 2

**Comment by ndcunningham** [comment]
was busy this week, pr is coming
