### ISSUE TITLE
Easy way to style autocomplete

### ISSUE THREAD

**Issue by joshterrill** [ng2-ui/ng2-auto-complete#144]
I'm using this in a project that requires the input to be styled a little bit. I've tried adding styles to the classes that get put on the elements, but it looks like the classes get put on the elements after a render because none of the styles are showing up. On my local copy, I've been working on figuring out a way to modify the code so that it can take some styes as an attribute on like `<input ng2-auto-complete custom-css="[{height: 70}, {width: 300}]">` however, when I set up the property to be able to be used in the component `ng2-auto-complete.directive.js` like `'customCSS': [{ type: core_1.Input, args: ["custom-css",] },],` it is being passed through as a string, and when I try to wrap it in `JSON.parse(this.customCSS)`, it says `invalid character h`.

Is this something that you would mind being added to the repo if I was able to figure this out? If so, do you know of a way that I would be able to have `custom-css="[{height: 70}, {width: 300}]"` and be able to use it as an actual array of objects in the component? Because I can't get that to work, I'm having to do something like `custom-css="height: 70px, width: 300px"` and creating an array by splitting the `,` and then lopping over that, and doing all sorts of weird trim/pop things to get the name/value out of it. Currently it works, but it seems really dirty...

What do you guys/gals think?

**Comment by allenhwkim** [comment]
@ndcunningham Could you create a custom css example?

**Comment by allenhwkim** [comment]
Please follow this plunker for custom css. It's also have been added to README.md

 http://plnkr.co/edit/0QFYFHMmCAFmhbYAGQl7?p=preview (With custom css)
