### ISSUE TITLE
built-in browser autocomplete hides ng2-auto-complete

### ISSUE THREAD

**Issue by youneschaoui** [ng2-ui/ng2-auto-complete#145]
How to hide built-in browser autocomplete. It hides ng2-auto-complete suggestions in a second layer

**Comment by allenhwkim** [comment]
I think you should not use built-in browser autocomplete for the input filed.

http://stackoverflow.com/questions/2530/how-do-you-disable-browser-autocomplete-on-web-form-field-input-tag

**Comment by youneschaoui** [comment]
there is no cross-browser way to hide turn off build-in browser autocomplete. my question is : how does ng2-auto-complete way to adapt to this reality ?

**Comment by allenhwkim** [comment]
@youneschaoui I am afraid ng2-auto-complete cannot to anything related to built-in browser feature unless there is a work-around provided.
