### ISSUE TITLE
AutoComplete with Observable not working

### ISSUE THREAD

**Issue by pdela** [ng2-ui/ng2-auto-complete#146]
With observables, list doesn't get filtered.
Look directly at your example of use with Observable. Autocomplete doesn't fire and the list doesn't get filtered.
http://plnkr.co/edit/uY3rsBg9F8aaoemP4Mjp?p=preview&open=app%2Fapp.component.ts

**Comment by allenhwkim** [comment]
Please be more specific. I do not understand what you mean.

**Comment by pdela** [comment]
Have a look at your example at plunker:

http://plnkr.co/edit/uY3rsBg9F8aaoemP4Mjp?p=preview&open=app%2Fapp.component.ts

Type in any number in the input box, the suggestion list doesn't get
filtered. All items are always visible, unlike all other examples you have
made.
See the screenshot.
Same behaviour replicated in my app when using Observables. All fine when
using arrays.

Regards,
Paolo



[image: Screenshot 2017-02-17 09.52.44.png]


Il giorno ven 17 feb 2017 alle ore 02:14 Allen Kim <notifications@github.com>
ha scritto:

**Comment by allenhwkim** [comment]
It's just matter of filtering with Observable. The previous example just shows all without filtering.
README.md is updated with plunker,   http://plnkr.co/edit/0C7vGDnhCKuMC5k2m2lR?p=preview&open=app%2Fapp.component.ts
