### ISSUE TITLE
Feature Request: option to allow Case Sensitive filtering

### ISSUE THREAD

**Issue by pdela** [ng2-ui/ng2-auto-complete#147]
Currently only case in-sensitive is supported

**Comment by allenhwkim** [comment]
I thought all auto complete is case insensitive.
Please provide a use case that requires case-sensitive search.

**Comment by pdela** [comment]
Hi Kim,

in my project I'm storing references to Firebase keys, which of course are
case sensitive.
I'm using autocomplete to search quickly among the available keys, but I
need it to be case sensitive.
I'm suggesting to add it just as an option to activate.

Thanks
Paolo


Il giorno ven 17 feb 2017 alle ore 02:16 Allen Kim <notifications@github.com>
ha scritto:

**Comment by allenhwkim** [comment]
Please use Observable as a source wisely to achieve case-sensitive filtering.

  http://plnkr.co/edit/0C7vGDnhCKuMC5k2m2lR?p=preview&open=app%2Fapp.component.ts
