### ISSUE TITLE
display-property-name is ignored if select-value-for is specified

### ISSUE THREAD

**Issue by youneschaoui** [ng2-ui/ng2-auto-complete#150]
display-property-name can't be changed if we specify a value of select-value-for

**Comment by allenhwkim** [comment]
Please provide a plunker example to reproduce your issue. It seems an obvious bug to you, but not to me and others.

FYI, 
`display-property-name` is not related to `select-value-of`.
https://github.com/ng2-ui/ng2-auto-complete/blob/2c9524fd16d85724d8663df0c62bcbff7d5ed4d8/src/ng2-auto-complete.directive.ts#L194

It is more related to `list-formatter` for dropdown list. It's to show dropdown list.

**Comment by allenhwkim** [comment]
Duplicate to #153

**Comment by youneschaoui** [comment]
the issue I am facing is that select-value-of is the same value used to display selected object is it possible for example to bind ngmodel to id and display selected object as username ?
