### ISSUE TITLE
very confusing properties select-value-of value-property-name display-property-name list-formatter

### ISSUE THREAD

**Issue by youneschaoui** [ng2-ui/ng2-auto-complete#153]
Consider the object :
`{'id':1, 'name':'easy'}`
how to configure ng2-auto-complete so that It shows name after selection and in suggestions. it binds to id value (not the hole object).

**Comment by allenhwkim** [comment]
select-value-of : the key name of object when selected 
value-property-name: NOT in use
display-property-name: what to show in your dropdown list as well as `list-formatter`.

Please provide a plunker example with your expectation.

**Comment by youneschaoui** [comment]
the issue I facing is that select-value-of is the same value used to display selected object is it possible for example  to bind ngmodel to id and display selected object as username  ?

**Comment by allenhwkim** [comment]
Yes possible. Please provide a plunker example with your expectation as it says at the issue template.

**Comment by youneschaoui** [comment]
**configuration**
` <input auto-complete
               no-match-found-text="nothing !" 
               class="form-control" 
               name="approver"
               list-formatter="username"
               select-value-of="id"
               [(ngModel)]="proposition.approver" 
               [source]="approvers" />`

**approvers**
`[{ "id": 1, "username":"younes"}]`

**Comment by allenhwkim** [comment]
Please provide a plunker example with your expectation as it says at the issue template.
