### ISSUE TITLE
Accept-user-input = false is not working with v 0.10.9

### ISSUE THREAD

**Issue by johnrayner** [ng2-ui/ng2-auto-complete#155]
Using ver 0.10.9 of ng2-auto-complete, all user input is accepted by the input control regardless of the value set on "accept-user-input".  Here is my plunk: http://plnkr.co/edit/UbGH3h.  Previous versions reverted invalid input when the field lost focus.

This is probably the same issue as https://github.com/ng2-ui/ng2-auto-complete/issues/122

**Comment by johnrayner** [comment]
Sorry, but that doesn't do what I need it to.  My application makes a XHR call to resolve the values that the user can pick.  So I need the user to be able to type into the control (the readonly setting stops this completely).  But if they tab out without picking a value, then whatever they've done with the control should be reverted.  This was the behavior of v0.8.2 and it rocked.  I'll see if I can make some changes to the source code and send you a PR.

**Comment by allenhwkim** [comment]
@johnrayner thanks for the explaining the use case for me.
I think you have a valid point.
Prior to v0.8.2, we have two input tags, then it changed to have only one input for simplicity.

Let me take a look into it later. Meanwhile a PR would be highly appreciated.

**Comment by allenhwkim** [comment]
This has been merged and deployed

**Comment by johnrayner** [comment]
Thank you!  When do you plan to push 0.10.10 to npm?

**Comment by allenhwkim** [comment]
@johnrayner didn't I?

**Comment by johnrayner** [comment]
@allenhwkim no ... https://www.npmjs.com/package/ng2-auto-complete says "0.10.9 is the latest of 50 releases"

**Comment by allenhwkim** [comment]
K, published now. Sorry about that

**Comment by riaadh** [comment]
Hi there, 
I also used accept-user-input = "false" and it's not working.  Like johnrayner  i need this 

> But if they tab out without picking a value, then whatever they've done with the control should be reverted. >  <

Thank you for your help

**Comment by allenhwkim** [comment]
Try this please. `[accept-user-input]="false"`

**Comment by riaadh** [comment]
@allenhwkim  thank you it works
