### ISSUE TITLE
Test code coverage 

### ISSUE THREAD

**Issue by nazrulcse** [ng2-ui/ng2-auto-complete#157]
Hi,

Test(Jasmine) code available for this. I am gating error in test code "Can't bind to 'source' since it isn't a known property of 'input'". Here is auto-complete code

<input type='text' ng2-auto-complete [(ngModel)]="geoAddress" placeholder="Address" 
                       [source]="googleGeoCode" no-match-found-text="Address Not Found"
                       list-formatter="formatted_address" path-to-data="results" loading-text="Searching..."
                       max-num-list="5" min-chars="2" class='form-control'
                       formControlName="address" autocomplete="false"             
                      (valueChanged)="addToAddrs($event)" 
                       [ngClass]="{'input-error': userForm.controls.address.invalid && submitted}"/>

Thanks

**Comment by allenhwkim** [comment]
Please be more specific. Please be  specific about what your environment is, what you did, and what you expected.

**Comment by allenhwkim** [comment]
Closing until the details are provided

**Comment by adtm** [comment]
Same issue.

Angular 4.
Expected to pass tests with Jasmine. A spec.ts file which tests component initialization (auto generated). Imported auto complete module to imports. 
Failed because of source is not a known property of input

**Comment by adtm** [comment]
Fixed, should have looked more carefully (:
