### ISSUE TITLE
Target specific field from Source to search

### ISSUE THREAD

**Issue by ohgasauraus** [ng2-ui/ng2-auto-complete#159]
**Current behavior**
If i have a complex source (USER: {USERID, USERNAME, DISPLAYNAME, EMAIL}) with multiple fields, auto complete will search thru every field including the field itself. 

**Expected/desired behavior**
Is it possible to only set the fields to search? Only search within DISPLAYNAME or EMAIL field

**Comment by allenhwkim** [comment]
Yes, you can use an Observable source to customize the search.

**Comment by webcat12345** [comment]
@allenhwkim , not sure about solution.

http://plnkr.co/edit/F9nrWp?p=preview

On this plunker, search is triggered with `name` , `population` and `id`. All fields. Is there any way to focus only `population` field?
