### ISSUE TITLE
Option to not draw list at all if there are no matches found.

### ISSUE THREAD

**Issue by jasonburrows** [ng2-ui/ng2-auto-complete#160]
When there are no matches there is an option to provide custom text ('no-match-found-text').

I'd prefer to simply not draw the list at all, but I can't find a way to configure for that.  If I provide nothing for 'no-match-found-text' it will still show the default text, and if I provide a space character (to ensure there is a valid string), it still draws the list - minimally, but it is still displayed as an empty list a few pixels in height.

Can we can an option to not draw the list on no matches, or simply don't draw the list when an empty string is passed for 'no-match-found-text'?

Thanks!

**Comment by allenhwkim** [comment]
Hmm, I am not sure this is very intuitive not to show any, but
you are still able to show nothing when no match found by overriding css.
I have added `no-match-found` class for that item.

.ng2-auto-complete ul li.no-match-found {display: none}

**Comment by allenhwkim** [comment]
@jasonburrows You can achieve this by adding css at this moment
```
.ng2-auto-complete ul li.no-match-found {display: none}
```

**Comment by jasonburrows** [comment]
I have tried this solution and it doesn't seem to have any effect.  It seems like `'display: inline-block'` is an inline style on `ng2-auto-complete` so adding the css you've provided doesn't take precedence over this.

...that being said even this has no effect: `.ng2-auto-complete ul li.no-match-found {display: none !important;}`

I must admit that I'm having trouble debugging it as when I use the Chrome developer tools I can't get the cursor to stay in the input field when I try to select the `ng2-auto-complete` element, regardless of what "Force element state" options I use on the input field it is associated with.

**Comment by jasonburrows** [comment]
Well, here's how to select that item - enter this into the debugger:
```
window.addEventListener('keydown', function(e) { 
  if (e.keyCode == 123) debugger; 
});

```
Then select the element using chrome's dev tools, and hit F-12.  This will cause javascript to stop while the debugger runs.  Then you can inspect the item.

There's no `no-match-found` class being applied to that list item.  `blank-item` seems to be the class that is applied.

So I've added the css `.ng2-auto-complete ul li.blank-item {display: none;}` which seems to work.  Let me know if this is going to have some undesirable side effect.

**Comment by allenhwkim** [comment]
@jasonburrows please use the recent release which has `no-match-found` class.
