### ISSUE TITLE
Chinese characters can not be inputted in Chrome by Keyboard.

### ISSUE THREAD

**Issue by eastjie** [ng2-ui/ng2-auto-complete#161]
Hallo, 

In this demo, I have tried to input with Chinese characters using keyboard. 
https://ng2-ui.github.io/dist/#/auto-complete

It doesn't work in Chrome (My version is 56.0.2924.87). There is no problem in Firefox and Edge.

Thanks.

**Comment by allenhwkim** [comment]
@eastjie thanks for reporting this.
I made some fix for this. please test it with 0.10.11, but not merged to ng2-ui.github.io yet.

**Comment by eastjie** [comment]
Thanks very much. I have tried the actual version and the problem is solved.
