### ISSUE TITLE
how can i update regex

### ISSUE THREAD

**Issue by hemant-chaudhary** [ng2-ui/ng2-auto-complete#162]
current regex used is (/:[a-zA-Z_]+/) i want to update in to (/\b[a-zA-Z_]+/) so that it only search from the beginning of the each word in string. 

Example:-
India - In
Australia - AU
America - US

so when i type I in input result should be only "India - In" not Australia or America 
or
if i type us it should only return America - US not A'us'tralia- AU even though Australia has us in it

Can you helps so that i can override the search  regex.

**Comment by allenhwkim** [comment]
Please use Observable source for customized search.
