### ISSUE TITLE
Feature Request: selected-value-formatter similar to list-formatter

### ISSUE THREAD

**Issue by dmostert** [ng2-ui/ng2-auto-complete#164]
**Current behavior**
It seems you can on bind to a simple property for `select-value-of`.

**Expected/desired behavior**
It would be great if the selected value can be formattet similar to the result from `list-formatter`.

**Usecase**
I can then store the selected object in code and have a friendly display string.

**Comment by allenhwkim** [comment]
@dmostert thanks for reporting this
Can you be more specific on this? I have a guess, but it would be better with an example.

**Comment by dmostert** [comment]
We have a number of lookup classes (`code`, `description`, ...) in our current system. I want to create Auto complete inputs for them.

Per convention we always show the lookup as `code ~ description`. - With the current `list-formatter`, this is trivial and is currently working.

After an item is selected, I would like to see `code ~ description` as the selected value.

I will store the selected code value elsewhere.


Hope this helps!

**Comment by allenhwkim** [comment]
0.11.0 released with this feature. please use `value-formatter`

**Comment by dmostert** [comment]
Thanks - it works
