### ISSUE TITLE
Autocomplete selected item

### ISSUE THREAD

**Issue by vadimaus** [ng2-ui/ng2-auto-complete#166]
Hello
Is there a function to return the currently selected item from the dropdown?
Following the documentation, I use (valueChanged)="this.onValueChanged($event), but the '$event' would return the value as I type, then I won't know which item user had selected.
Am I doing something wrong there?

Thanks in advance
Vadim

**Comment by allenhwkim** [comment]
@vadimaus Thanks for the feedback, I will look into it.

**Comment by allenhwkim** [comment]
Are you using the most recent version, It did not happen to me.
http://plnkr.co/edit/MDvZUj?p=preview

**Comment by allenhwkim** [comment]
Closing this. Please reopen this problem still continues

**Comment by vadimaus** [comment]
@allenhwkim Looks like we have different versions of ng2-ui. The same code works fine in plunker but not on my local env.  However, when I run "npm outdated" it doesn't list it in the outdated packages, which means I have the latest one.
Could you tell me which version did you use in the above example?
Thanks

**Comment by allenhwkim** [comment]
@vadimaus Are you using `ng2-ui` module or `ng2-auto-complete`? `ng2-ui` is not always up-to-date with dependency modules, but `ng2-auto-complete` is.

**Comment by vadimaus** [comment]
@allenhwkim I referenced  ng2-ui  because I use the popup from there as well. Would it be possible to update it, at least for now? 
Thank you

**Comment by allenhwkim** [comment]
Yes, I will do soon. Thanks for your patiencte

**Comment by allenhwkim** [comment]
`ng2-ui` has been upgraded.

 ng2-auto-complete    0.11.0  →  0.11.1
 ng2-datetime-picker  0.14.6  →  0.14.7
 ng2-map              0.16.2  →  0.16.3
