### ISSUE TITLE
use with formControlName instead of ngModel?

### ISSUE THREAD

**Issue by mickeychu** [ng2-ui/ng2-auto-complete#17]
First of all thank you for your auto-complete. really useful!!!!

However, I created the form in my app using the **formControl** so with input, I can not use **ngModel** but **formControlName**. 

When I select an item from the dropdown, it's not updated on the input, still show whatever the initial **formControlName** were.

Is there anyway to make the autocomplete work with **formControlName**?

**Comment by allenhwkim** [comment]
Could you create a plnkr example for this?

**Comment by mickeychu** [comment]
ah, never mind. I just add ngModel along with formControlName and everthing works ok: 

`<input auto-complete formControlName="building" [(ngModel)]="myForm.value.building" [source]="buildings" display-property-name="buildingAddress" />`

Cheers!!!!
