### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by crh225** [ng2-ui/ng2-auto-complete#172]
Is it possible to show all items, but have a fixed height list of items with a scrollbar?

**Comment by allenhwkim** [comment]
Yes, just manipulate your css.

**Comment by crh225** [comment]
I have added
```
.ng2-auto-complete ul {
height: 100px;
overflow-y: auto;
}
```
to my scss file that uses the autocomplete. I am not able to see the scrollbar

**Comment by crh225** [comment]
Do you have any tricks to leaving the dropdown list always open for dubugging? if I try to inspect element of the autocomplete dropdown, it registers as a click in chrome, and keeps hiding the dropdown.

**Comment by allenhwkim** [comment]
plz try like the following,
```
.my-div .ng2-auto-complete ul {
  height: 100px;
  overflow-y: auto;
}
```
About, forcing it to open, you can set a break point on this line, 
https://github.com/ng2-ui/ng2-auto-complete/blob/master/src/ng2-auto-complete.directive.ts#L106

**Comment by saurabhkumar11** [comment]
When Start typing, first in the list is auto selected and hit the enter, text box is filled with first item. i did not want it to fill textbox on enter like Jquery Autocomplete.

**Comment by allenhwkim** [comment]
@saurabhkumar11 thanks for the feedback. Could you please create a separate issue for that.

**Comment by crh225** [comment]
@allenhwkim it is not working for me. Here is my html and css
```
                                <span *ngIf="row.isNew" class="auto-complete-wrapper">
                                    <input auto-complete class="form-control control-borderless search-watermark" id="gs1{{i}}" type="text"
                                           placeholder="{{ 'FILTER' | translate:lang }}"
                                           (valueChanged)="rowModelChange($event,growthTable,i)"
                                           [ngModel]="row"
                                           value-property-name="code"
                                           display-property-name="name"
                                           no-match-found-text="{{ 'PDTABLE_NO_MATCH' | translate:lang }}"
                                           [list-formatter]="autocompleListFormatter"
                                           [source]="getfilteredRowHeaders.bind(this,growthTable)"
                                           [accept-user-input]="false"
                                           [max-num-list]="10">
                                </span>
```
```.auto-complete-wrapper .ng2-auto-complete ul {
  height: 100px;
  overflow-y: auto;
}
```

**Comment by crh225** [comment]
here is a screenshot of the rendered html
![image](https://cloud.githubusercontent.com/assets/19475195/24359473/159a0d6e-12ca-11e7-821a-1200fe880bac.png)

**Comment by allenhwkim** [comment]
@crh225 please crate a minimal plunker example for this, which is not working.

**Comment by crh225** [comment]
http://plnkr.co/edit/4zSFNaSNavA2NA5SHx0I?p=preview

**Comment by allenhwkim** [comment]
http://plnkr.co/edit/ye2WV6?p=preview. When override css, it's better to do it in index.html

**Comment by crh225** [comment]
I understand that is one way to do it, but it should work the angular way with the inline styles. I have not had to do this with other modules.

**Comment by allenhwkim** [comment]
@crh225 for that case, you have to add `ViewEncapsulation: None` for your component.

http://plnkr.co/edit/6axhO7?p=preview

**Comment by crh225** [comment]
thanks
