### ISSUE TITLE
how to use "value-changed" and "value-property-name" ?

### ISSUE THREAD

**Issue by mickeychu** [ng2-ui/ng2-auto-complete#18]
> value-changed, function variable name, callback function that is executed when dropdown is selected. e.g. myCallback, not myCallback

I don't see the different between the **e.g** and the **not**. 

Can I use it like **(value-changed)="myFunction(id)"** or it's just function name only, no parameters sending with it is accepted?

And for **value-property-name**, what ever key name I assigned to this, it still bind the whole object to the ngModel. I just want to bind the key **buildingID**, not the whole object.

`value-property-name="buildingID"`

**Comment by allenhwkim** [comment]
`(value-changed)="myFunction"` is correct, so that internally it can execute `myFunction(value)`

about `value-property-name`, if your object is {foo:1, var:'name 1'}, `foo` should be the `value-property-name` and `foo` should be `display-property-name`.

display-property-name and value-property-name is used for dropdown to determine what to show, not for ngModel. whenever you choose something, whole object will be assigned as ngModel; ` {foo:1, var:'name 1'}`

your `value-changed` function be useful if you want to do more; e.g. `valueChanged(object)`

**Comment by allenhwkim** [comment]
I think it's better to change `value-chnaged` from input to output. IMO

**Comment by mickeychu** [comment]
I can not use anything except the **value** with ` myFunction(value)`.

If I try to call another function from my component, it will be **undefined**

```
myFunction(value){
    this.getApartments(value.buildingID);
}
```

**Comment by allenhwkim** [comment]
The first value would be undefined. Please follow this example.

https://plnkr.co/edit/s9mBPJ?p=preview

**Comment by mickeychu** [comment]
I mean the **this.getApartments()** function is undefined .

I want to call a function like this: 

```
import {Component, NgModule} from '@angular/core';
import {BrowserModule} from '@angular/platform-browser';
import {FormsModule} from '@angular/forms';
import {Ng2AutoCompleteModule} from 'ng2-auto-complete';
import {HttpModule} from '@angular/http';


@Component({
  selector: 'my-app',
  templateUrl: './src/app.tpl.html'
})
export class App {
  public arrayOfKeyValues2: any[] = [
    {key:1, name:'Key One'}, 
    {key:2, name:'Key Two'}, 
    {key:3, name:'Key Three'},
    {key:4, name:'Key Four'}
  ];
  
  public model3;
  
  valueChanged(val) {
    this.log(val);
  }
  
  log(val) {
    alert(JSON.stringify(val));
  }
}

@NgModule({
  imports: [ 
    BrowserModule,
    FormsModule,
    HttpModule,
    Ng2AutoCompleteModule
  ],
  declarations: [ App ],
  bootstrap: [ App ]
})
export class AppModule {}
```

**Comment by kodeine** [comment]
the problem is, `valueChanged` function returns the object inside the component, so if you do 
```
  valueChanged(val) {
    alert(JSON.stringify(val));
    console.log(this); <--- this is the object of autocomplete object not the class App 
  }
```
I assume its a bug.

**Comment by mickeychu** [comment]
Yeah, I did try to `console.log(this);` 

So is there anyway to fix this?

**Comment by allenhwkim** [comment]
I am going to change this from `@Input` to `@output`, so that this problem goes away
Meanwhile, try this plz
```

valueChanged = (val) => {
    alert(JSON.stringify(val));
    console.log(this); <--- this is the object of autocomplete object not the class App 
}
```

**Comment by kodeine** [comment]
@mickeychu 
as a temporary fix i just added a formControlName in the and subscribe to the control value. But since @allenhwkim has updated, we should be good to go with that.

**Comment by mickeychu** [comment]
Thanks @kodeine  :) 

I think I will wait for the update from @allenhwkim.

Cheers!!!!

**Comment by kodeine** [comment]
@allenhwkim is this issue updated?

**Comment by allenhwkim** [comment]
This has been changed with 0.6.1 release

Before

    [value-changed]="myCallback"

After

    (value-changed)="myCallback($event)"
