### ISSUE TITLE
"BrowserModule has already been loaded"

### ISSUE THREAD

**Issue by noxborough** [ng2-ui/ng2-auto-complete#22]
If you import Ng2AutoCompleteModule into an NgModule that already imports BrowserModule (which will be pretty much any angular2 app).  You get this error message, because i believe BrowserModule can only be imported once.

It seems like a better idea for Ng2AutoCompleteModule to import CommonModule instead.

The current design pretty much prohibits you from importing Ng2AutoCompleteModule into any child module.

The point i'm trying to make is confirmed in this stackoverflow post (look at accepted answer):
http://stackoverflow.com/questions/39414231/angular2-rc6-importing-browsermodule-in-my-submodules

thoughts?

**Comment by allenhwkim** [comment]
Ok, I will try with `CommonModule`

**Comment by allenhwkim** [comment]
released it with 0.6.4

**Comment by noxborough** [comment]
thank you, it works perfectly now.
