### ISSUE TITLE
Dropdown psotioning and size

### ISSUE THREAD

**Issue by lovjith** [ng2-ui/ng2-auto-complete#23]
Is it possible to position the dropdown dynamically according the available height of the container (if the available height is less then dropdown should be displayed on top of the text box)?
It would have been better if there is property to specify the the max height for the dropdown.

**Comment by allenhwkim** [comment]
Isn't it doing? `ng2-datetime-picker` does that already. If not, I will borrow that idea from there.

**Comment by lovjith** [comment]
Please find the below pictures and the [**plunker is here**](http://plnkr.co/edit/K7ndR0qb63qkZH27aGGx)

**ng2-auto-complete**
![image](https://cloud.githubusercontent.com/assets/16626186/18606751/3d14b578-7cc1-11e6-82b5-9353fc127625.png)

**Html Select**
![image](https://cloud.githubusercontent.com/assets/16626186/18606761/7cc890ae-7cc1-11e6-87de-48ee13b77567.png)

**Comment by allenhwkim** [comment]
This has been fixed and released with 0.7.0. Please verify the change and close it.
