### ISSUE TITLE
Creates an input inside an input ??

### ISSUE THREAD

**Issue by gotenxds** [ng2-ui/ng2-auto-complete#25]
Hi, Im trying to use your library and I get this behavior, 
when just pasting your code 

`<input auto-complete [(ngModel)]="myData" [source]="mySource" />`

Into my html template I get this as the end result:

![image](https://cloud.githubusercontent.com/assets/3519520/18808590/e4f6a73a-826e-11e6-844b-c9e67d879653.png)

Which is an input witin an input, this makes things really difficult when I use a styled input like in this picture:

![image](https://cloud.githubusercontent.com/assets/3519520/18808597/0d60d240-826f-11e6-83a9-656626e9df0f.png)

As you can see, this is really awkward,

**Comment by allenhwkim** [comment]
This is the default style. You can override it easily. Without having a separate input, it should intervene the original value of input(which is text), and it was hard to go back when typed `esc` or when cancel the search.
``
  .auto-complete input {
    outline: none;
    border: 2px solid transparent;
    border-width: 3px 2px;
    margin: 0;
    box-sizing: border-box;
    background-clip: content-box;
  }
``

The current design is to separate the user input and the autocomplete input. The default style is to fully cover user input when autocomplete input is triggered. 

If it's hard to build custom styling, please create a plunker for it. I can help or treat it as a bug.
