### ISSUE TITLE
angular 2 final intergration?

### ISSUE THREAD

**Issue by mickeychu** [ng2-ui/ng2-auto-complete#26]
How to make this work with Angular 2 final (2.0.1) ? thank you!

I got an error when import the module in AppModule:

![screen shot 2016-09-27 at 12 43 40](https://cloud.githubusercontent.com/assets/7807777/18869952/3dd0d34a-84b7-11e6-90a0-34ac0533afce.png)

**Comment by allenhwkim** [comment]
It's already working with 2.0. Did you follow README.md install part?

**Comment by mickeychu** [comment]
Yes, I did reinstall the package and followed the instruction  in README.md (except the `systemjs.config.js` part). But still the same error :(

**Comment by kodeine** [comment]
@allenhwkim i am facing the same issue. As soon i include in imports, i get the same error.

**Comment by allenhwkim** [comment]
Is this 2.0.1 only issue? How come I don' t have that error in 2.0.0 env?
Can someone give me more detail about this error in step by step?

**Comment by kodeine** [comment]
https://github.com/qdouble/angular2webpack2-starter

Just clone that starter and add autocomplete module, ull see the error.

**Comment by allenhwkim** [comment]
Is this specific to webpack?

If you are using webpack to run this, `systemjs.config.js` is not useful to define where `ng2-auto-complete` is. For me, I resolve this by where the packaged is in `webpack.config.js`. For example.

```
  /**
   * Resolve
   * Reference: http://webpack.github.io/docs/configuration.html#resolve
   */
  config.resolve = {
    alias: {
      'ng2-ui': root("node_modules", "ng2-ui", "dist", "ng2-ui.umd.js")
    },
    // only discover files that have those extensions
    extensions: ['', '.ts', '.js', '.json', '.css', '.html']
  };

// Helper functions
function root(args) {
  args = Array.prototype.slice.call(arguments, 0);
  return path.join.apply(path, [__dirname].concat(args));
}
```

There must be better solution for this when we use webpack. If so, please LMK.

**Comment by kodeine** [comment]
@allenhwkim usually for other packages we dont have to define them in webpack, we just install via npm and import the package index into the app. Are we missing something?

**Comment by kodeine** [comment]
also i still get the same error even though i've setup webpack to

```
    alias: {
      'ng2-auto-complete': root("./node_modules/ng2-auto-complete/dist/ng2-auto-complete.umd.js")
    },
```

**Comment by allenhwkim** [comment]
I think it's worth trying to have `index.ts` on the root level of `node_modules/ng2-auto-complete` as the same as `@angular/common` does

**Comment by kodeine** [comment]
@allenhwkim i agree with you. lets do that. because it should be plug and play.

**Comment by allenhwkim** [comment]
This has  been implemented with the new release. Please verify the change.
