### ISSUE TITLE
Cannot search for a result when autocomplete does not return any value

### ISSUE THREAD

**Issue by seustachi** [ng2-ui/ng2-auto-complete#28]
When I type in the search box, I expect that if no match is found by auto-complete, I can still launch a search with the string I typed. This does not seem possible here, as ngModel is only updated when I select an item in the list.

I would expect the component to store what I typed, in order to be able to launch a "normal" search (like if autocomplete did not exist).

**Comment by seustachi** [comment]
One possible solution would be to have Keyword as an Output (event could be emitted in reloadList()), so we could bind to a variable in the component (it is like have another ngModel, one for the result of the search, one for the user input)

**Comment by allenhwkim** [comment]
For this case, it's better to be able to select blank item like the same as `select` tag.

![image](https://cloud.githubusercontent.com/assets/1437734/19017698/c33cdf4e-8811-11e6-9533-175149d877d1.png)

**Comment by allenhwkim** [comment]
This has been fixed and released with 0.7.0 with having new option `blank-option-text`. Please verify the change and close it.
