### ISSUE TITLE
Problems with OPTIONS request(desapeared)

### ISSUE THREAD

**Issue by kolyan131313** [ng2-ui/ng2-auto-complete#3]
I have updated autocomplete module to 0.2.0 versions from 0.1.6 and i haven't seen sending OPTIONS request to server, i can't get data from server. Could you check and fix if it posible. At 0.1.6 version it has worked perfect

**Comment by allenhwkim** [comment]
I did not get what you exactly meant. For me, this example works fine by sending a keyword to a server. https://plnkr.co/edit/32syXF?p=preview

Can you explain your issue with this plunker?

**Comment by allenhwkim** [comment]
I also checked the diff, and there is not much difference https://github.com/jsvalley/ng2-auto-complete/compare/0.1.6...master

**Comment by kolyan131313** [comment]
ok, i will check it on more

**Comment by kolyan131313** [comment]
You can see my problems in your plunker, in browser console - network option. Earlier your module sent several requests(first - OPTIONS request, second- GET request), but now we can see one request

**Comment by kolyan131313** [comment]
in your case its works, but in my case i need one more request(OPTIONS), as it was earlier.
If it posible, could you fix it

**Comment by allenhwkim** [comment]
Could you paste your screenshot here?

**Comment by allenhwkim** [comment]
AFAIK, OPTIONS request are not decided by this module. Even with 0.1.6, only GET request is sent to Google 

![image](https://cloud.githubusercontent.com/assets/1437734/16542709/7e835806-4081-11e6-9f4c-4afa505e060e.png)

For CORS, OPTIONS request are sent to check if it is safe to send request. Ref.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS.

To solve this, I need more detail about your request to server.

**Comment by butenkoder** [comment]
Hi guys. I have same problem, i can't use my HTTP_PROVIDERS because your provider use instead of my native. Earlier in v0.1.6 you didn't use this provider for your method.
And I use provider for RequestOptions in main.ts file for adding additional headers for request. In v0.1.6 we could see our autorization headers, but start from v0.2.0 we can't send our headers in requests

**Comment by butenkoder** [comment]
Could you fix it asap?

**Comment by allenhwkim** [comment]
ok I will remove HTTP_PROVIDERS dependency, test, and release ASAP

**Comment by butenkoder** [comment]
ok, thanks

**Comment by allenhwkim** [comment]
tagged and published as 0.4.1. Please let me know how it goes

**Comment by butenkoder** [comment]
thanks, it works perfect. Thanks for help
