### ISSUE TITLE
plunker example current is not working

### ISSUE THREAD

**Issue by jairoGilC** [ng2-ui/ng2-auto-complete#31]
The plunker example defined in the documentation is not working

    TypeError: Zone.assertZonePatched is not a function
    NgZoneImpl@https://npmcdn.com/@angular/core/bundles/core.umd.js:6197:13 
    NgZone@https://npmcdn.com/@angular/core/bundles/core.umd.js:6346:30

**Comment by allenhwkim** [comment]
Thanks for reporting this. I will make a fix soon

**Comment by allenhwkim** [comment]
Plunker is updated as http://plnkr.co/edit/3pB1Gx?p=preview
