### ISSUE TITLE
Usage with bootstrap input-group

### ISSUE THREAD

**Issue by adros** [ng2-ui/ng2-auto-complete#32]
I'd like to use ng2-auto-complete with bootstrap's 'input-group' feature (class)

http://v4-alpha.getbootstrap.com/components/input-group/#basic-example

But after the input is wrapperd into another 2 elements, the styling is broken.

```xml
<div class="input-group">
  <span class="input-group-addon">@</span>
  <auto-complete style="...">
    <div class="auto-complete">
      <input class="form-control" ...>
```

Is there any workarund how could I make it work?

**Comment by allenhwkim** [comment]
The only way I can see is to define `.form-control` css
