### ISSUE TITLE
can't shift+tab to a previous field

### ISSUE THREAD

**Issue by iamthewinnar** [ng2-ui/ng2-auto-complete#33]
When you you tab or click on the autocomplete field if you try to shift+tab to go to the previous field it just resets the autocomplete search, presumably because it's tabbing back to the initial autocomplete field   and then creating a new autocomplete input each time.

**Comment by allenhwkim** [comment]
This has been updated with new release 0.7.3. Please verify the changes

**Comment by iamthewinnar** [comment]
I can confirm that this is resolved now.
