### ISSUE TITLE
Module ..../node_modules/ng2-auto-complete/dist/ng2-auto-complete.umd.js does not export Ng2AutoCompleteModule 

### ISSUE THREAD

**Issue by queejie** [ng2-ui/ng2-auto-complete#34]
I am using Ionic 2 RC0, which uses Angular 2.  I'm not sure if this is an environmental issue or a problem with the component.  One difference is that there is no system.config.js in the Ionic app that I can find.

**Comment by allenhwkim** [comment]
Are you using webpack?

**Comment by allenhwkim** [comment]
This should have been fixed with the recent release for webpack users. Please verify the change.
