### ISSUE TITLE
Can't bind to 'source' since it isn't a known property of 'input'

### ISSUE THREAD

**Issue by Chabane** [ng2-ui/ng2-auto-complete#35]
Hi,

Thanks for the job,

I tried to integrate the auto-complete, but I got this error : 

`Can't bind to 'source' since it isn't a known property of 'input'`

```
 <input auto-complete formControlName="itemControl" [(ngModel)]="itemSelected" [source]="items" placeholder="Select an item"
      />
```

How can I do to ignore this error?

Thanks

**Comment by Chabane** [comment]
I forgot to export Ng2AutoCompleteModule

**Comment by azjkjensen** [comment]
@Chabane will you elaborate on what the problem was and how you fixed it?

**Comment by rsheptolut** [comment]
@Chabane yeah, would be good to know, because I'm struggling with the same issue now. There's nothing about exporting Ng2AutoCompleteModule in the Install section of the README.md of ng2-auto-complete repository...

**Comment by teleuko** [comment]
In my case I forgot to add "ng2-auto-complete" to the input tag

**Comment by adtm** [comment]
Bump, same issue

**Comment by Steven-Garcia** [comment]
Bump, same issue, I have done all the steps and and added "ng2-auto-complete" to the input tag

**Comment by allenhwkim** [comment]
I think the problem is that your input tag may not have `ng2-auto-complete` or your application did not include this module.

**Comment by Steven-Garcia** [comment]
Both things were done as explained on https://www.npmjs.com/package/ng2-auto-complete, module was correctly imported from app.module.ts and the template included the tag

**Comment by allenhwkim** [comment]
@Steven-Garcia please reproduce your example with plunker. I guess you are missing this line, but it might be different. https://github.com/ng2-ui/auto-complete/blob/master/app/main.ts#L32

**Comment by Steven-Garcia** [comment]
Ok, just managed to sort it, as it turns out to be, when in a big application with separate packages, it's not enough with importing the dependency in the app.module.ts  It also needs to be imported in the FooPackage.fooClass.module.ts
  Thank you for coming to the rescue so quickly!

**Comment by mobixdev** [comment]
Hope people don't mind the length of this but I sometimes find it hard when only a snippet is provided, so I'm hoping this makes sense.
I copied this from a working example [https://www.tomislavstankovic.com/blog/ionic3-autocomplete/](url)

my structure
Folder: auto-complete
auto-complete.ts
auto-complete.scss
auto-complete.module.ts
auto-complete.html

I had imported to the app.module.ts 
`import { RlTagInputModule } from 'angular2-tag-input';`
also within the imports on that page 
```
imports: [
    BrowserModule,
    FormsModule,
    IonicModule.forRoot(MyApp),
    AngularFireModule.initializeApp(FIREBASE_CONFIG),
    AngularFireAuthModule,
    AngularFireDatabaseModule,
    ComponentsModule,
    HttpModule,
    AgmCoreModule.forRoot({
      apiKey: GOOGLEMAP_CONFIG.googleMapsKey
    }),
    RlTagInputModule
  ],

```
What I had forgotten to do was import to auto-complete.module.ts 
```
import { NgModule } from '@angular/core';
import { IonicPageModule } from 'ionic-angular';
import { AutoCompletePage } from './auto-complete';
import { RlTagInputModule } from 'angular2-tag-input';

@NgModule({
  declarations: [
    AutoCompletePage,
  ],
  imports: [
    IonicPageModule.forChild(AutoCompletePage),
    RlTagInputModule
  ],
})
export class AutoCompletePageModule {}
```
Once I did that it worked fine.

auto-complete.ts
```
import { Component } from '@angular/core';
import { IonicPage, NavController, NavParams } from 'ionic-angular';

@IonicPage()
@Component({
  selector: 'page-auto-complete',
  templateUrl: 'auto-complete.html',
})
export class AutoCompletePage {

  public autocompleteTags = [];
  public autocompleteItems = [
    'Array of names',
    'Array of names',
    'Array of names',
    'Array of names',
    'Array of names',
    'Array of names'
  ]; //for test purpose only

  constructor(public navCtrl: NavController, public navParams: NavParams) {
  }

  ionViewDidLoad() {
    console.log('ionViewDidLoad AutoCompletePage');
  }

}
```
auto-complete.html
```
<ion-header>

  <ion-navbar>
    <ion-title>AutoComplete</ion-title>
  </ion-navbar>

</ion-header>


<ion-content padding>

    <ion-item no-padding>
      </ion-item>
        <rl-tag-input
          [addOnBlur]="false"
          [autocomplete]="true"
          [autocompleteItems]="autocompleteItems"
          [(ngModel)]="autocompleteTags"
          placeholder="Start typing a name">
        </rl-tag-input>
      <br><hr>
      <ion-list>
        <ion-item text-wrap>
          <h2>Name:</h2>
          {{autocompleteTags | json}}
        </ion-item>
      </ion-list> 

</ion-content>
```
