### ISSUE TITLE
Decouple the "keyword" word

### ISSUE THREAD

**Issue by SadatAnwar** [ng2-ui/ng2-auto-complete#36]
Hello, 
I recently tried this auto-complete out, and I must give you fair warning, I am a total Angular2 noob, I tried out a few auto-complete to get one working, but I think this is pretty cool, only one slight issue I feel I have. My data source is a GET http. so I followed the google api example, and it works, but I feel its rather annoying to use `:keyword` as a fixed string, maybe you can make this some sort of a variable, that can be defined in the template or something more flexible. 
Also if its already possible, would love to know how. 

Cheers! 

PS: I am using the latest (0.7.3)

**Comment by allenhwkim** [comment]
Thanks for feedback

It's not possible at this moment, https://github.com/ng2-ui/ng2-auto-complete/blob/f8eca078844099f186a735244e5bb4c9fc420088/src/ng2-auto-complete.component.ts#L199

It takes `keyword` to complete the remote call.

I will mark it as a new feature.

**Comment by corner22** [comment]
I too would like this feature.  I have a WebAPI method that needs the keyword parameter to be named 'textToMatch' in the URL.

**Comment by dberthia** [comment]
Excuse the confusion, but I don't understand the :keyword usage. 

I have a URI like so **http://foo?q=100**, where the q param contains the text to search for. For it to work with your component, do I need to modify my URI to be **http://foo?q=:keyword**? Does the component substitute the entered value for ":keyword"? I can't seem to figure out the right combo to get this to work.

**Comment by allenhwkim** [comment]
As you see here in the example, 
https://github.com/ng2-ui/ng2-auto-complete/blob/master/app/app.component.ts#L49 and 
https://projects.invisionapp.com/share/ZJ98MKE3D#/screens/202679153, 
:keyword is the search text you entered into your input field that will be replace by every remote call.

**Comment by allenhwkim** [comment]
How about changing `:keyword` to any uppercase text followed by colon `:`. e.g. `:KEYWORD`, `:ANY_WORD`, `:MY_VAR`, or `:ANY_UPPERCASE_LETTER_VARIABLE`?

**Comment by dberthia** [comment]
My input field looks like this:
`           <input
                ng2-auto-complete
                [(ngModel)]="internalidtext"
                [source]="matterTypeaheadUrl"
                display-property-name="number"
                value-property-name="number"
                type="text"
                id="internalidtext"
                formControlName="internalId"
                [attr.aria-required]="true" />
 `
and matterTypeAheadUrl = 'http://foo?q=:keyword'

Unfortunately it doesn't make any REST calls as I type. What am I missing?

**Comment by allenhwkim** [comment]
this new feature is release with 0.7.8
