### ISSUE TITLE
Support to add entry even if its not present in source

### ISSUE THREAD

**Issue by SadatAnwar** [ng2-ui/ng2-auto-complete#37]
not sure if its already possible, but would be awesome to have an option to enable input if its not part of the lookup source. (to add a new value)

**Comment by allenhwkim** [comment]
Do you mean by program or by manual input?

**Comment by adomasbc** [comment]
I think what @SadatAnwar meant was that for example source is ['a','b','c'] and I want to enter custom value 'd'. Currently the value of the field has to be one from the source and it does not allow adding extra value or assigning some new custom value to binded var.
