### ISSUE TITLE
How to use with wikipedia api

### ISSUE THREAD

**Issue by Mike6g** [ng2-ui/ng2-auto-complete#38]
Hello,

First of all, good job!

I tried to play with this module, it works well when the resource is local, or when the JSON retrieved is complete, however is it possible to make it work with the wikipedia api ?
https://en.wikipedia.org/w/api.php?action=opensearch&format=json&limit=5&search=angular
It basically returns an array.

API Info here: https://en.wikipedia.org/w/api.php

In advance, thanks a lot !

**Comment by allenhwkim** [comment]
`src="https://en.wikipedia.org/w/api.php?action=opensearch&format=json&limit=5&search=:keyword"` should work

**Comment by Mike6g** [comment]
No success with Version 0.7.4
`<input auto-complete
          [source]="wikipediaCode"
          [(ngModel)]="nameWiki"
          placeholder="enter Name"
          min-chars="2"
          /> `
`wikipediaCode: string = "http://fr.wikipedia.org/w/api.php?action=opensearch&format=json&search=:keyword";

Any suggestion ?
  `

**Comment by allenhwkim** [comment]
You have CORS issue. I wish I could help with that, but I cannot. It's a security matter.

![image](https://cloud.githubusercontent.com/assets/1437734/19525721/e7459d2c-95ef-11e6-8ab7-df1f1ab6358d.png)

http://plnkr.co/edit/4giwxebK9cDBWEsLGayC?p=preview

**Comment by Mike6g** [comment]
Hello,

Thank you for you quick answer.
The observable approach does not work, since the component calls the service I use using 'this' as itself, and then can not use the jsonp.
I'll post my wikipedia solution if I get it to work :-D

Also, I can not get to work the valueChanged parameter, but I didn't see the @Input property in the component (on the master branch)

Regards

**Comment by Mike6g** [comment]
Alright !!
I finally managed !!
Here is my final solution !
https://plnkr.co/edit/UymsymM2zJH61uQnQ2wA?p=preview

Trick: `ngOnInit(): void {
    this.getItems = this._getItems.bind(this); // Here is the trick !
  }`
Hope this helps

**Comment by allenhwkim** [comment]
Ok, you resolved CORS with jsonp, nice. 

You can directly define the function without binding it again using arrow function.

https://plnkr.co/edit/wQOd0P?p=preview

    getItems = (keyword:string): Observable<string[]> => {
    	return this.wikipediaService.find(keyword);
    }

@boban984, Could you figure out why this requires arrow function?

**Comment by boban984** [comment]
Hey guys ... the arrow function is used so it can trap the "this".
Because the function for reading the Observable is called from the Ng2-Autocomplete component so the function "getItems" actually uses that "this" instead of the "this" from the component that holds the input.

For now this is the way to do this, i could refactor part of the autocomplete to support  the calling of the function without using arrow functions but that would require using a different approach.
Instead of passing the "function" as a value using [] ... if we passid as an even using () it will work as expected.
