### ISSUE TITLE
(change) event is not triggered after selecting an options

### ISSUE THREAD

**Issue by well-made** [ng2-ui/ng2-auto-complete#39]
I have to following code as an example:
`<input type="text" class="form-control" placeholder="Partner" auto-complete [source]="filters.merchants" (change)="filterOrders('merchant.id', $event.target.value)"/>`

In my component I have a `console.log` in the `filterOrders` function, but it isn't triggered.
Seems like the `(click)` gets removed when creating the ng-auto-complete element?

**Comment by allenhwkim** [comment]
`(change)` is for the input field.
While auto-complete is on display, there user input field is not used. there is another input field will be displayed on the top of user input field as an overlay.

Thus, please follow these options. I recommend (valueChanged)="myFunc($event)"

https://github.com/ng2-ui/ng2-auto-complete#attributes

**Comment by well-made** [comment]
Thanks, that does the trick.
Sorry I missed that option in the documentation.
