### ISSUE TITLE
[value-changed] gets executed a 1000 times

### ISSUE THREAD

**Issue by JunusErgin** [ng2-ui/ng2-auto-complete#4]
I implemented something like this:
```
  <input
    auto-complete
    [(ngModel)]="result"
    [source]="states"
    [display-property-name]="'name'"
    [value-changed]="search()"
    [min-chars]="3"
    class="form-control"
    placeholder="Search...">

```
The function` search() `gets executed a 1000 times immediately. It should only be executed when I type or remove a letter, right?

The search function should update the source "states" every time I type in a letter. 

Thanks for your support in advance!

Junus Ergin

**Comment by JunusErgin** [comment]
I just saw I misunderstood the function:
    `[value-changed]="search"` should be written like this and only be executed when sth. in the dropdown menu is selected.

**Comment by allenhwkim** [comment]
Thanks
I don't see `this` as in `should be written like this`. Did you make a PR?

**Comment by allenhwkim** [comment]
I misunderstood ur statement. Yes [value-changed] is not an event but a property.
