### ISSUE TITLE
Overwrite "Loading" text

### ISSUE THREAD

**Issue by ajyadav013** [ng2-ui/ng2-auto-complete#40]
Is there any way to overwrite the text "loading" while fetching data with remote source as HTTP URI string?

**Comment by allenhwkim** [comment]
That is hard coded. You can override it with css. e.g. text color as transparent and a background.

**Comment by ajyadav013** [comment]
I would like to contribute... :)

**Comment by allenhwkim** [comment]
Thanks, This is the example that I created without any code change.
http://plnkr.co/edit/vHagLx?p=preview

**Comment by well-made** [comment]
@ajyadav013 any update on your contribution?

Would also be nice if it is possible to change text if no results are found in the source.

**Comment by allenhwkim** [comment]
Fixed, and will be released soon.

**Comment by well-made** [comment]
Thanks :)
