### ISSUE TITLE
Tabbing out of the autocomplete field does not remove the select list field when no text is entered.

### ISSUE THREAD

**Issue by iamthewinnar** [ng2-ui/ng2-auto-complete#41]
When using the auto complete, if you tab out of the field without entering any data the select input does not go away. (the loading box does). It does however work properly if you click out of the field. Clicking also works if you've already tabbed out of the field to another field.

**Comment by allenhwkim** [comment]
This seems like a bug, although it is trivial. `(blur)` should fire an event to hide component, not only dropdown to the directive.

**Comment by iamthewinnar** [comment]
It looks like blur is firing correctly. From what I can tell it looks like that when you click off the element the following directive function is being called: hideAutoCompleteDropdown(). However when you tab off this function is not called. 

https://github.com/ng2-ui/ng2-auto-complete/blob/master/src/ng2-auto-complete.directive.ts#L66

**Comment by allenhwkim** [comment]
Yes that `blur`, https://github.com/ng2-ui/ng2-auto-complete/blob/master/src/ng2-auto-complete.component.ts#L20,  event should end up hideAutoCompleteDropDown() ,https://github.com/ng2-ui/ng2-auto-complete/blob/master/src/ng2-auto-complete.directive.ts#L112. We need to look into this for a simple and proper solution.

**Comment by allenhwkim** [comment]
Is this still a bug? It seems working for me

**Comment by iamthewinnar** [comment]
It seems like it is currently working, at least within chrome.

**Comment by allenhwkim** [comment]
Closing for now
