### ISSUE TITLE
Inject Authentication Credentials into the request header of source URL

### ISSUE THREAD

**Issue by corner22** [ng2-ui/ng2-auto-complete#42]
I have a WebAPI method that I call to get my autocomplete list.  This method is protected by OAUTH2 authentication, so in order to call it I need to inject authentication credentials into the request header (to be specific, i need to add a Bearer token as an Authorization header) but ng2-auto-complete does not provide a way to do this. (unless I'm missing something?).

Would it be possible to provide a mechanism to modify http GET request headers before calling the URL?

(I have worked around this issue for now by removing the authorization requirement for my WebAPI method, so it's not a show-stopper for myself right now.  However, I can see it being a show-stopper for other people).

**Comment by allenhwkim** [comment]
You are not missing, you cannot add Bearer token only using http url.

However, you still can use Observable method to modify your header. When you fully download this and run a server using `npm start`, you will see the example using Observable.

https://github.com/ng2-ui/ng2-auto-complete/blob/master/app/app.component.ts#L55
https://github.com/ng2-ui/ng2-auto-complete/blob/master/app/app.service.ts#L24

**Comment by corner22** [comment]
Thanks for the info.  The Observable way resolves my issue.

**Comment by corner22** [comment]
Thanks Allen. That looks like just the thing I need. Will give it a go with
my webapi and I'll let you know how I get on.
