### ISSUE TITLE
Webpack integration

### ISSUE THREAD

**Issue by andreroggeri** [ng2-ui/ng2-auto-complete#44]
My question may be silly, but the readme.MD only explains how to use this directive on SystemJS, and since the angular-cli is using webpack to generate the builds I have no clue on how to use this directive.

I tried to:

1. Install it using `npm install ng2-auto-complete --save` and importing on my module
*Results on module not found*

2. Add the mapping on `angular-cli.json` to `"../node_modules/ng2-auto-complete/dist/ng2-auto-complete.umd.js"`
*It throws an exception `Uncaught TypeError: Cannot read property 'Injectable' of undefined`*

So, could you please help with the usage on Webpack ? (Once I understands how it works I can send a PR to update the readme)

**Comment by allenhwkim** [comment]
Strange, it works for me

![image](https://cloud.githubusercontent.com/assets/1437734/19672254/cd85fdc6-9a42-11e6-8ded-d0e1c4424c1f.png)


```
diff --git a/package.json b/package.json
index 1e28e4f..1862919 100644
--- a/package.json
+++ b/package.json
@@ -37,6 +37,7 @@
     "karma-cli": "^1.0.1",
     "karma-jasmine": "^1.0.2",
     "karma-remap-istanbul": "^0.2.1",
+    "ng2-auto-complete": "^0.7.4",
     "protractor": "4.0.9",
     "ts-node": "1.2.1",
     "tslint": "3.13.0",
diff --git a/src/app/app.component.html b/src/app/app.component.html
index b6931b5..51ec0f6 100644
--- a/src/app/app.component.html
+++ b/src/app/app.component.html
@@ -1,3 +1,6 @@
 <h1>
   {{title}}
 </h1>
+
+<input auto-complete [(ngModel)]="myData" [source]="mySource" />
+
diff --git a/src/app/app.component.ts b/src/app/app.component.ts
index ff63e05..a727f22 100644
--- a/src/app/app.component.ts
+++ b/src/app/app.component.ts
@@ -7,4 +7,5 @@ import { Component } from '@angular/core';
 })
 export class AppComponent {
   title = 'app works!';
+  mySource = [1,2,3,4,5,6,7];
 }
diff --git a/src/app/app.module.ts b/src/app/app.module.ts
index 67ae491..4dc45c7 100644
--- a/src/app/app.module.ts
+++ b/src/app/app.module.ts
@@ -2,6 +2,7 @@ import { BrowserModule } from '@angular/platform-browser';
 import { NgModule } from '@angular/core';
 import { FormsModule } from '@angular/forms';
 import { HttpModule } from '@angular/http';
+import { Ng2AutoCompleteModule } from 'ng2-auto-complete';

 import { AppComponent } from './app.component';

@@ -12,7 +13,8 @@ import { AppComponent } from './app.component';
   imports: [
     BrowserModule,
     FormsModule,
-    HttpModule
+    HttpModule,
+    Ng2AutoCompleteModule
   ],
   providers: [],
   bootstrap: [AppComponent]
```

**Comment by allenhwkim** [comment]
@bipulkdas, I heard you have an issue with webpack. Please take look at my solution

**Comment by andreroggeri** [comment]
I did the same steps that you and worked on a clean env. 

I'll try again later on my dev env and if still an issue I'll open again

**Comment by martinpring** [comment]
@andreroggeri I know this issue is closed but I have the same problem. It worked on a clean env but I struggle to get it to work on my dev env. Did you get it to work?
