### ISSUE TITLE
Autocomplete based on first letter?

### ISSUE THREAD

**Issue by AlexTamminen** [ng2-ui/ng2-auto-complete#45]
Would it somehow be possible to get the auto complete to do the search based on first letter? I mean I have hundreds of data, so it is not so ideal when the search is not based on first letter. Tried looking into the package and do some modifications myself on the regex, but didn't succeed. Keep in bind that I'm a newbie, hehhe.

Any help would be appreciated!

**Comment by ajyadav013** [comment]
auto-complete [(ngModel)]="selectedCategory" [source]="Url" min-chars="4" display-property-name="name" auto-complete-placeholder="Hello" (valueChanged)="callFunctionAfterValueChanged()" />

Referring above, change the min-chars value to 1.

**Comment by allenhwkim** [comment]
Please remind that there is Observable solution, which you can do anything for your search result.

**Comment by AlexTamminen** [comment]
@ajyadav013 I have tried this with different min-chars value. But it still searches every word with those entered letters. E.g with min chars 1 search letter "t" gives all words with "t" in it. Search by "te" gives all words with "te" in it. Example from own data: "bad tastTE in mouth", "changed TExture in hair" and so on. I would like it to search words that START with "t" and words STARTING with "te" and not where the "te" occurs in ANY place of the word!

@allenhwkim I don't know what you mean, could you elaborate?

**Comment by allenhwkim** [comment]
@AlexTamminen please look at this example, 

https://angular.io/docs/ts/latest/api/forms/index/FormGroupName-directive.html
and 
https://github.com/ng2-ui/ng2-auto-complete/blob/master/app/app.service.ts#L24

You can do anything like you would do with string from your input.
```
    findHeroes = (startsWith: string): Observable<any[]> => {
        return this._http.get(`${this.marvelBase}characters?nameStartsWith=${startsWith}&apikey=${this.marvelPublicKey}`)
        .map(h => h.json())
        .catch(e => console.error(e));
    } 
```
