### ISSUE TITLE
auto complete not show when access input field by pressing tab

### ISSUE THREAD

**Issue by bdsettrade** [ng2-ui/ng2-auto-complete#46]
I use your auto complete in form and using tab to select next input field.
I found that if I click on input the auto complete will show but if I go to next input field by pressing tab the auto complete will not work. Do you have any suggestion?

**Comment by allenhwkim** [comment]
Thanks for using it. Are you using old version? I see tab is working with the recent version with Chrome browser.

http://plnkr.co/edit/3pB1Gx?p=preview

**Comment by bdsettrade** [comment]
Thanks, it works :D. 
My version is 0.6.4. After I change it to 0.7.4 , the problem is gone.
