### ISSUE TITLE
Limit list items

### ISSUE THREAD

**Issue by ermansan** [ng2-ui/ng2-auto-complete#48]
How can I limit the number of items to show (with scrollable bar)? Is it possible?

**Comment by allenhwkim** [comment]
it's possible with Observable.
There is no property setup for that feature at the moment.

**Comment by ermansan** [comment]
I've noticed that for width it is limited to div dimension but I need the height limitation. I've tried with several css configuration but nothing. Any suggestion?

**Comment by allenhwkim** [comment]
You can override style
```
    <style>
      ng2-auto-complete ul {
        height: 50px; overflow: auto;
      }
    </style>
```

**Comment by allenhwkim** [comment]
Deployed, will be released soon

**Comment by amineparis** [comment]
@allenhwkim  `max-height ` insead this way not found text doesn't contain a lot of whitespace whatever the value we put
