### ISSUE TITLE
Default value for ngModel and FormGroup

### ISSUE THREAD

**Issue by gectus** [ng2-ui/ng2-auto-complete#49]
Hi! 
I have a problem. Now if I initialize the model object with FormGroup, I'm getting "[object] [object]"
Example: http://plnkr.co/edit/qGT7NoWKMdpl1Ue0RXxF?p=preview

**Comment by gectus** [comment]
Without FormGroup all OK
http://plnkr.co/edit/fznmxDa6MXVIaR8y80X2?p=preview

**Comment by allenhwkim** [comment]
I am not an expert on this matter. I haven't used formGroup.  https://angular.io/docs/ts/latest/api/forms/index/FormGroupName-directive.html

Any help would be appreciated.

**Comment by ndcunningham** [comment]
I think the page construction is incorrect.

FormsModule and ReactiveModule are two different approaches to forms. Though they can co-exist that doesn't mean it is the right approach.

`ngModel` is a part of FormsModule and should be used _inside a FormsModule form_ or incase you want a simple two way binding on a page for an input element.

Here is a snippet from Angular University about the two:

> Note that ngModel can still be used with model driven forms. Its just that the form value would be available in two different places: the view model and the FormGroup, which could potentially lead to some confusion.
> Due to this reason mixing ngModel with reactive forms is best avoided.

http://blog.angular-university.io/introduction-to-angular-2-forms-template-driven-vs-model-driven/

I think if you want a page with a lot of state interactivity work with ReactiveModule else go FormsModule

**Comment by allenhwkim** [comment]
Nico, thanks 

You just have me bunch of things to read.
Can you make a specific suggestion or a PR?

**Comment by ndcunningham** [comment]
No problem.

I read through the source, the provided plnkr and realized that the page was indeed wrong.

@gectus Please see the updated plnkr: http://plnkr.co/edit/xPVNrtnBAExBBaHs2KAL?p=preview, Is this what you wanted to do?

@allenhwkim PR may not be necessary.

When using `ReactiveFormsModule` you need to tell the page the exact value you are binding. If you use an object you either need to create a pipe or transform the object yourself.

Regardless keep `ngModel` and `formControlName` in separate forms respectively. Makes troubleshooting easier along with many other things.

**Comment by gectus** [comment]
Hi all

@ndcunningham 
it will serve
Thanks a lot!

**Comment by allenhwkim** [comment]
ReadMe.md is updated with this example, and closing it
