### ISSUE TITLE
Exception thrown when tried to include the "ng2-auto-complete" as nested component

### ISSUE THREAD

**Issue by lovjith** [ng2-ui/ng2-auto-complete#5]
I created 'AnalysisPickerComponent' which contains "ng2-auto-complete". Then I tried to include the 'AnalysisPickerComponent' inside my 'HomeComponent'.

Component nesting order: 'HomeComponent' -> 'AnalysisPickerComponent' -> 'ng2-auto-complete'

**EXCEPTION: Error: Uncaught (in promise): Unexpected directive value 'undefined' on the View of component 'AnalysisPickerComponent'**

**Comment by allenhwkim** [comment]
Thanks for using this module.

My guess is that your AnalysisPickerComponent did not import AutoCompleteComponent properly.
If you create a plunker, it will be very helpful to debug.

**Comment by lovjith** [comment]
Dear Allen Kim

Thank you very much for the reply and highly appreciate it.

I solved it already just now. I imported *HTTP_PROVIDERS* into
AnalysisPickerComponent and everything worked fine.

Regards

Lovjith K T

The reason was

Phone: *+966 59 889 9982*, +971 50 888 7695, +91 811 181 4444

2016-07-22 0:04 GMT+03:00 Allen Kim <notifications@github.com>:

**Comment by allenhwkim** [comment]
Glad you find the solution. If you don't mind, could you star this repo for other developers?
