### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by beradrian** [ng2-ui/ng2-auto-complete#51]
Hi,

I have a few question:
- How can I use a method that returns an Observable as the source? Is there an example?
- How can I customize the list? I guess '.ng2-auto-complete ul li'.

**Comment by allenhwkim** [comment]
1. Yes. Please see app directory
2. to customize list, use `list-formatter`. For css, just override css that is used  in component, https://github.com/ng2-ui/ng2-auto-complete/blob/master/src/ng2-auto-complete.component.ts

**Comment by beradrian** [comment]
There's also another issue that appears in the demos too. If I enter something, select a suggestion and then click back again on the input, the input disappears. I saw in the code that is using two inputs - can I drop off the second one?

**Comment by allenhwkim** [comment]
@beradrian no, that input is for `ng2-auto-complete` dropdown input which is different from user input. This is designed to separate user input field and `ng2-auto-complete` input. The recent release keeps your input as it is unless you specify `accept-user-input="false"`
