### ISSUE TITLE
Webpack support?

### ISSUE THREAD

**Issue by bendg25** [ng2-ui/ng2-auto-complete#58]
Hi

I am using webpack and am getting this error when trying to do a production build:

Unexpected value 'Ng2AutoCompleteModule' imported by the module 'AppModule'

Do you support webpack?

**Comment by allenhwkim** [comment]
Yes, it support webpack, and I have tested it with min. 2 times with webpack.

**Comment by kkotak** [comment]
I think this error is related to compiling Angular-cli with AOT. Any thoughts?

**Comment by ShadowManu** [comment]
Our team is using this Module with `angular-cli` and it works on normal builds. However, it does not work when specifically using it with AOT. I'll open an issue and PR later today or tomorrow about this, since our team needs it ;)

**Comment by allenhwkim** [comment]
Thanks @ShadowManu
