### ISSUE TITLE
How to specify the width of the auto complete control

### ISSUE THREAD

**Issue by lovjith** [ng2-ui/ng2-auto-complete#6]
Please guide me how to specify the width of auto complete relative to the container such as 100% or 80%

Also it be great if more documentation is provided

Here is my plunker [ng2-auto-complete on plunker](http://plnkr.co/edit/0R8Zix?p=preview)

Thanks

**Comment by allenhwkim** [comment]
You just add a style

http://plnkr.co/edit/2CHZPS?p=preview

at the bottom of style.css

```
div.ng2-auto-complete {
  width: 100%;
}
```

**Comment by allenhwkim** [comment]
I will add more document for this.

**Comment by lovjith** [comment]
Thank you very much. Already the component has all the necessary features. Definitely with the documentation will take it to the new heights

**Comment by rennyatwork** [comment]
Could you apply the style?

My problem is: 
1) I want a label to be side by side with the ng2-auto-complete.
2) If I solve 1), I end up having the autocomplete list not aligned with the auto-complete input.

Here is my css:
.champTexteRecherche {
    width:200px;
    height: 30px;
    margin-right: 10px;
    font-size: 13px;    
    float:left;  //--> with this, I can put side-by-side, however, autocomplete list is not aligned anymore
    margin:10px;
}

and here is my html:

 <div class="rechercheUtilisateurInterieur">
                    <div class="search">
                        <label class="boldElement"
                               for="searchLogon"
                               style="display:inline-block">Search a user:</label>
                    </div>
                    <div style="padding-top:10px;">
                        <input ng2-auto-complete
                               id="searchLogon"
                               [(ngModel)]="selectedItem"
                               ngModel name="event"
                               #event="ngModel"
                               [source]="userList"
                               value-property-name="userCode"
                               display-property-name="userCode"
                               (valueChanged)="myCallback($event)"
                               min-chars="2"
                               no-match-found-text="No result"
                               loading-text="en chargement"
                               [list-formatter]="autocompleListFormatter"
                               placeholder="Logon"                                
                               />
                    </div>


I have a component with its own css.

I tried applying div.ng2-auto-complete {
  width: 100%;
}

however, it not worked.

Could you please help me on this? Thanks
