### ISSUE TITLE
Support for allowing items not in the list

### ISSUE THREAD

**Issue by kkotak** [ng2-ui/ng2-auto-complete#61]
It seems like currently you don't support binding new items to the model, thereby allowing users to input a value not found in the dropdown.

**Comment by aberonni** [comment]
I'd be interested in this too. 

In my case I wouldn't want to add user's input to model, but simply give the user the possibility to enter something that isn't in the model.

**Comment by allenhwkim** [comment]
@boban984 Can you design this for me?

**Comment by allenhwkim** [comment]
this has been implemented
