### ISSUE TITLE
AoT Compatibility

### ISSUE THREAD

**Issue by ShadowManu** [ng2-ui/ng2-auto-complete#66]
As initially mentioned in #58, this package is not compatible with AoT compiler, at least the `angular-cli` AoT loader, specifically with the error `Unexpected value 'Ng2AutoCompleteModule' imported by the module 'AppModule'`.

Looks like something related to publish a `metadata.json` file generated by the angular compiler, as mentioned in angular/angular#11262.

I'll add a PR for this when I start having some results.

**Comment by ShadowManu** [comment]
oh well... After 3 small nights fighting on the compilers and webpack, I think I got it. I'll be posting the PR now.

**Comment by allenhwkim** [comment]
PR is merged
