### ISSUE TITLE
Problem with data binding for the first time 

### ISSUE THREAD

**Issue by paria-tk** [ng2-ui/ng2-auto-complete#69]
I've used the auto complete in a tab component. 
First time that i click on the input the list is empty but if i click somewhere and click again on the input, it is working. 

this is html template:
```
 <input auto-complete 
                   [source]="manufacturerList"                               
                   [(ngModel)]="model3"
                   display-property-name="Name"
                   placeholder="Select a Vendor"
                   name="vendor"
                   class="form-control"/>
```

this my component:

```
export class FootprintGeneralComponent {

    manufacturerList: any[]= [];
    model3 = "";
    constructor(private footprintService: FootprintService) {    
    }

    ngOnInit() {
       this.footprintService.getManufacturers(value)
            .subscribe((res: any[]) => {
                console.log(res);
                this.manufacturerList = res;
            },
            error => {
                console.log('Failed to load values. ' + error);
            });
    }
  ```

**Comment by paria-tk** [comment]
it should implements  OnInit
export class FootprintGeneralComponent implements OnInit {

**Comment by allenhwkim** [comment]
My guess is your `manufacturerList` has not been executed when you click autocomplete.
However, I want you to create a plunker for us to debug properly.

**Comment by allenhwkim** [comment]
This will be closed  soon if we do not have a clear way to reproduce your issue with a plunker example.

**Comment by labibismaiel** [comment]
I am facing the same issue, and it's exactly as described above, if the data is coming async, the first click inside the input will not show anything (even after the data is available), and if you click outside (to lose focus) then inside again, it starts working normally

**Comment by allenhwkim** [comment]
Thanks for reporting this. However, if your source is changed by observable, your source must be an observable type, not a static one.
