### ISSUE TITLE
Get current dropdown list

### ISSUE THREAD

**Issue by mhakir** [ng2-ui/ng2-auto-complete#70]
Hi,

First, great package!

Second, I have a question...

How can I get/retrieve the current items in the dropdown list and update my value on every change?

Thanks in advance!

Kind regards,
Matthias

**Comment by allenhwkim** [comment]
Thanks, but I do not understand your question.
what does current items mean?

**Comment by mhakir** [comment]
With current items, I mean the suggestions listed in the dropdown when typing in the input.

![image](https://cloud.githubusercontent.com/assets/24419524/20959199/08f8d87c-bc5a-11e6-8bec-3366e79984e9.png)
The items/objects/list/array in the red section.

Does this clarify?

**Comment by mhakir** [comment]
Can someone help me please?

Thanks in advance!

**Comment by allenhwkim** [comment]
That's your source, and it should be in your code. From the following example, your current items are specified in `arrayOfStrings`
```
    <input 
      ng2-auto-complete
      [(ngModel)]="model1"
      [source]="arrayOfStrings" /> 
```

About `and update my value on every change`, what is `my value`? on what is `every change`?

Do you mean when auto complete dropdown is selected how do you update your value? It's done automatically.

**Comment by mhakir** [comment]
The "source" are all items. I want the current items visible in the dropdown.
Let's say I have an array of 100 items specified as "source" and I also use "max-num-list='10' ".
How can I get the 10 current, visible items?

Thanks in advance!

**Comment by allenhwkim** [comment]
What does 'current' mean?

**Comment by allenhwkim** [comment]
Do you 10 items matching your search criteria?

**Comment by mhakir** [comment]
Yes

**Comment by allenhwkim** [comment]
It's `filteredList` of the dropdown component. A dropdown component is dynamically created and removed and currently it's not exposed out side of a directive.

https://github.com/ng2-ui/ng2-auto-complete/blob/master/src/ng2-auto-complete.component.ts#L132

To be frankly, I do not see use cases of needs to see the source of dropdown list at the moment.

**Comment by mhakir** [comment]
I wanted to use it to update my table beneath it.
