### ISSUE TITLE
Issue while remote data errors

### ISSUE THREAD

**Issue by surjitkumar25** [ng2-ui/ng2-auto-complete#73]
How to pass authorization header for remote data?

**Comment by allenhwkim** [comment]
You can use observable. Please take a look at examples;

html here, 
https://www.duolingo.com/skill/fr/Basics-1

and Javascript here, 
https://github.com/ng2-ui/ng2-auto-complete/blob/master/app/app.service.ts#L24

You can set the header as the same as other angular2 http call
