### ISSUE TITLE
focusout event

### ISSUE THREAD

**Issue by sudhirroy-tudip** [ng2-ui/ng2-auto-complete#77]
Hey, I need a focus out event. Actually, what I am trying to do is that when user write something that is not in my whole list, I just empty that data.So, how can I do that?

**Comment by allenhwkim** [comment]
Sorry I have just updated README.md

* `**accept-user-input**` boolean, if false and does not match to source given, it goes back to the original value selected.

Is this what you are looking for?

**Comment by sudhirroy-tudip** [comment]
Thank you man
