### ISSUE TITLE
Working with reactive forms issue.

### ISSUE THREAD

**Issue by Efactor888** [ng2-ui/ng2-auto-complete#78]
Hello!

I been playing around with this and I reviewed the plunker example, however I cannot get the result from the dropdown to be inputted in the model per Form's control. 

Based on the example link provided, by entering different values from the drop down selecting in the Form Control, it does not update the model. Just wondering how this will work with reactive forms.

http://plnkr.co/edit/CxeAHUgeNfH25Cp7RM43?p=preview

Thank you,
Erik

**Comment by allenhwkim** [comment]
@ndcunningham We need to have better example for this reactive forms. I think people are still confused between model and form control.

**Comment by Efactor888** [comment]
Thank you  allenhwkim  and @ndcunningham, I believe I figured out a way to do this.

In the html input, I used the valueChanged method:
`<input formControlName="countries" ng2-auto-complete [source]="testdata" (valueChanged)="myCallBack($event)">`

Then I wrote a function to update the form control by patchValue:

`myCallBack(newVal) {
    return this.form.patchValue({customer: newVal})
  }`
