### ISSUE TITLE
When setting the mouse on somewhere within the string, it goes immediately goes to the end of the string

### ISSUE THREAD

**Issue by sherm84** [ng2-ui/ng2-auto-complete#79]
Expected: the cursor will remain at the same place and you'll be able to type.

**Comment by ndcunningham** [comment]
can you provide a plunkr of this?

**Comment by allenhwkim** [comment]
This is intended behaviour to sepearte user input field from autocomplete input field. I am not sure this is worth to fix unless there are many upvotes.
