### ISSUE TITLE
valueChanged emits when typing

### ISSUE THREAD

**Issue by andreroggeri** [ng2-ui/ng2-auto-complete#80]
I was at 0.7.4 and after upgrading to 0.8.1 the behavior of valueChanged is different. (IDK if this was intended)

On 0.7.4, the valueChanged is only emited when a item from the list is selected

On 0.8.1 the valueChanged is emited every time the user types on the input.

Check the behavior below:

**0.7.4**

![](http://g.recordit.co/KlrBYpaXnc.gif)

**0.8.1**

![](http://g.recordit.co/FhpsyNB3zn.gif)

**Comment by andreroggeri** [comment]
I think its related to [this change](https://github.com/ng2-ui/ng2-auto-complete/blob/0.7.8/src/ng2-auto-complete.directive.ts#L168).

It seems that a condition is missing on that line

**Comment by allenhwkim** [comment]
This change is to accept user input although it is not listed on the list.
If you want to limit your input only from the list, as like in 0.7.4,  `accept-user-input` as false, so that it only fire once.

**Comment by andreroggeri** [comment]
Ah, makes sense.

Thanks ! =)
