### ISSUE TITLE
How to set width 100% with md-input?

### ISSUE THREAD

**Issue by askaFed** [ng2-ui/ng2-auto-complete#81]
I have the same issue as here #59 .
 I want to use your directory with md-input (line 2 should look like line 1 on the print screen).

![screenshot_7](https://cloud.githubusercontent.com/assets/16210354/21343103/d85bb826-c69d-11e6-88f5-8be62f01ae36.png)

Could you give me some advice how to fix my code?

>  
            
            <table style="width: 100%" cellspacing="0">
              <tr>
                <td>
                  <md-input  style="width: 100%" name="one" id="one" [(ngModel)]="searchItem.one"  #one="ngModel" required >
                    <md-placeholder>
                      <i class="material-icons app-input-icon">assignment</i> Md-input 1
                    </md-placeholder>
                  </md-input>
                </td>
                <td>
                  <md-input  style="width: 100%"  name="two" [(ngModel)]="searchItem.two" id="two"  #two="ngModel" required >
                    <md-placeholder>
                      <i class="material-icons app-input-icon">assignment</i> Md-input 2
                    </md-placeholder>
                  </md-input>
                </td>
              </tr>
            </table>

>  
          
            <table style="width: 100%" cellspacing="0">
              <tr>
                <td>
                  <md-input style="width: 100%"
                            ng2-auto-complete  [source]="cities"
                            name="one" id="one" [(ngModel)]="searchItem.one"  #one="ngModel"
                            value-property-name=""
                            display-property-name="name"
                            [accept-user-input]="false"
                            blank-option-text="Not selected" required >
                    <md-placeholder>
                      <i class="material-icons app-input-icon">assignment</i> Autocomplete 1
                    </md-placeholder>
                  </md-input>
                </td>
                <td>
                  <md-input style="width: 100%" ng2-auto-complete  [source]="cities"
                            name="two" id="two" [(ngModel)]="searchItem.two"  #two="ngModel"
                            value-property-name=""
                            display-property-name="name"
                            [accept-user-input]="false"
                            blank-option-text="Not selected" required >
                    <md-placeholder>
                      <i class="material-icons app-input-icon">assignment</i> Autocomplete 2
                    </md-placeholder>
                  </md-input>
                </td>
              </tr>
            </table>

and my css is
> 
       ng2-auto-complete,  input {
             display: block; border: 1px solid #ccc; width: 100%;
           }
      md-input {
           width: 100% !important;
         }

**Comment by allenhwkim** [comment]
A Fix has been made and published as 0.8.3, please verify the changes.
