### ISSUE TITLE
Format of item data in list

### ISSUE THREAD

**Issue by VitaliyKovtun** [ng2-ui/ng2-auto-complete#82]
Hey, can I display only value without an id of an item? If I have [{id: 1, name: 'name'}], and I need only to display name without (id), what should I do? Thank you.

**Comment by allenhwkim** [comment]
there is `list-formatter` as yo see in README.md
```
list-formatter, function variable name, custom list formatting function.e.g. 'myListFormatter', not 'myListFormatter()'
```

**Comment by VitaliyKovtun** [comment]
Oh, ok. Thank you.
