### ISSUE TITLE
In autocomplete, I need my ngModel value to be as 'Id' not as 'text'.Help me solve this!!

### ISSUE THREAD

**Issue by subhani1249** [ng2-ui/ng2-auto-complete#83]
Hi, 
![autocomplete](https://cloud.githubusercontent.com/assets/10893928/21453336/fcba5522-c933-11e6-9c73-8b98dfab371f.png)
I have used like this . in my ng model i am getting text(display-property-name) in my ngModel variable. , but i need value (value-property-name) in my ngModel variable.

<input class="form-control" auto-complete [(ngModel)]="sortObj.ResponsibleId" [source]="individuals"
                                                 display-property-name="EmployeeGroupName"  value-property-name="EmployeeGroupId"  accept-user-input="true"/>

2. How to set width 100% ?

**Comment by allenhwkim** [comment]
1.
Thanks for using this module. You can see your ngModel value by using ``{{sortObj.responsibleId | json}}. If your type of ngModel is an object, e.g. a JSON,  you will see an object, if not, you will see a string. 

2. You can override your css. For example, 

```
.my-div .ng2-auto-complete{
  width: 100%;
  input{
    width: 100%;
  }
}
```

**Comment by allenhwkim** [comment]
Closed for inactivity

**Comment by BaamAadmi** [comment]
Hi,
Can anyone explain me how to use an id as ngModel value and text in the dropdown, just like how we do in any html select. 
Thanks in advance.
Sudeep
