### ISSUE TITLE
call to authenticated search api fails as it requires auth header

### ISSUE THREAD

**Issue by nov10** [ng2-ui/ng2-auto-complete#85]
Currently `ng2-auto-complete.ts > getRemoteData()` allows only string source i.e. url to api.
Is there a way to route function returning observable as a source. This way it can go through our custom httpService and auth header will be sent along.
If not possible, is there way to add header to search calls explicitly ?

**Comment by allenhwkim** [comment]
Yes you can use observable as source. Please refer to the source at app directory

**Comment by nov10** [comment]
Can you point me to a sample for that. Since `ng2-auto-complete.ts > getRemoteData(keyword: string): Observable<Response> {` takes string as input. How to pass my own component observable function `getSuggestions` to `[source]` input of ng2-auto-complete in html.

```
home.component.html ::
<input ng2-auto-complete
          [(ngModel)]="model4"
          placeholder="Enter Address(min. 2 chars)"
          [source]="getSuggestions" >
```

```
home.component.ts ::
getSuggestions(input : string) : Observable<any>{
  return this._httpService.getSuggestions(apiUrl, ...)
}
```

**Comment by allenhwkim** [comment]
As you see `[source]` can be your own observable
```
    <h3>With Remote Source as Observable "Marvel API" </h3>
    <input  ng2-auto-complete
      id="model5"
      placeholder="Start typing a hero name (min. 2 chars) ... for example: Hulk"     
      [(ngModel)]="model5" 
      [source]="appSvc.findHeroes"  
      [list-formatter]="renderHero"
      path-to-data="data.results"
      min-chars="2" 
    />
```

appSvc.findHeroes:
```
    findHeroes = (startsWith: string): Observable<any[]> => {
        return this._http.get(`${this.marvelBase}characters?nameStartsWith=${startsWith}&apikey=${this.marvelPublicKey}`)
        .map(h => h.json())
    }
```

**Comment by kootenpv** [comment]
It's not a complete example. 

What does `data.results` have to do with anything?

I created:

```
findHeroes = (keyword: any) => {
    return Observable.of(["aa", "bb"]);
  }
```
