### ISSUE TITLE
If Used model driven approach then form.values is not getting updated.

### ISSUE THREAD

**Issue by hibumbapartha** [ng2-ui/ng2-auto-complete#86]
It is working fine with ngModel but with formControlName it does not change the form values

**Comment by allenhwkim** [comment]
@ndcunningham this is related to reactive form too. I would appreciate if you take a look into it.

**Comment by ndcunningham** [comment]
Will do @allenhwkim

**Comment by ndcunningham** [comment]
close? OP can reopen if issue is still around

**Comment by allenhwkim** [comment]
implemented. and closing.

**Comment by Drol** [comment]
form.values are updated. But form.dirty, form.pristine and form.invalid is not changed. I guess other statuses is not set either.
