### ISSUE TITLE
How to format vaue-property-name and display-property-name?

### ISSUE THREAD

**Issue by sudhirroy-tudip** [ng2-ui/ng2-auto-complete#87]
how can we edit vaue-property-name and display-property-name? Actually, I am implementing for country.
So, my abbreviation is (IN) and value is (INDIA). It  is displaying in list like "(IN)INDIA". I want to add space such that It looks like "(IN)   INDIA". For every country and state, I want to do same.How can we do that?
Can you help me please?

**Comment by allenhwkim** [comment]
There is `list-formater` as you can see in README.md

   *  list-formatter, function variable name, custom list formatting function.e.g. 'myListFormatter', not     'myListFormatter()'
