### ISSUE TITLE
Feature request: typeahead in input field with first result from autocomplete list

### ISSUE THREAD

**Issue by seadour** [ng2-ui/ng2-auto-complete#88]
This would take the first match from the autocomplete list and fill in the rest of the input field in a lighter text color.

I made a mockup in Photoshop to demonstrate:

![screen shot 2017-01-05 at 6 24 36 pm copy](https://cloud.githubusercontent.com/assets/6138182/21705470/00ff5dd0-d375-11e6-92a3-ead2beab9201.png)

**Comment by allenhwkim** [comment]
Thank you, but, I don't understand few things.

1. What if text we display on the list is different from the text user enters? This modules allows the custom formatting of the list item using `list-formatter`.
2. Why this feature is good for users? If we highlight text, then it makes more sense. This is google places auto complete example.
![image](https://cloud.githubusercontent.com/assets/1437734/21734682/a1138824-d432-11e6-908c-ec1de671c6be.png). This still does not answer the qustion 
3. What if user presses down arrow key by selecting the next item, still showing the first item?

**Comment by seadour** [comment]
In answer to your questions:

1. Do you mean, for example, if the user started typing "house" and the first match was "The White House"? In this case...I'm not sure. I guess my example would only work if the match was from the first character in the item. So perhaps this feature would only work in that case.

2. I like your example too. I also think this would be valuable.

3. Then, the field would fill in the full item string.

Another example of this "typeahead" functionality is in most browser URL fields -- just start typing something, and it will autofill from your history. For example, here are a couple screenshots from my browser (Google Chrome / Webkit). The blue highlighted portions were autofilled by the typeahead feature.

![screen shot 2017-01-09 at 4 03 32 pm](https://cloud.githubusercontent.com/assets/6138182/21788765/50cf8d0e-d685-11e6-9f9c-920cdea72dc3.png)

![screen shot 2017-01-09 at 4 03 56 pm](https://cloud.githubusercontent.com/assets/6138182/21788769/5495424e-d685-11e6-845d-0da25d8c567d.png)

**Comment by allenhwkim** [comment]
This is a good feature. However, it won't be implemented sooner. I will close for now this and reopen when there are more requests.
