### ISSUE TITLE
Value getting blank of AutoComplete using form control(Form Group)

### ISSUE THREAD

**Issue by smartHasmukh** [ng2-ui/ng2-auto-complete#91]
I have tried to use autocomplete input in form control for choose city. autoComplete working but when I have choose city then submit form then city is getting blank.

HTML CODE

```
<form class="form-horizontal" [formGroup]="myForm" (ngSubmit)="onSubmit(myForm.value)">
    <div>
        <div class="col-sm-5">
            <input  ng2-auto-complete
                   formControlName="city"
                   [source]="cityList"
                   [list-formatter]="autocompleListFormatter"
                   value-property-name="id"
                   display-property-name="name"
                   placeholder="City"
                   class="form-control">
        </div><br/>
        <button type="submit">Submit</button>
    </div>
</form>

```

TYPESCRIPT CODE

```
public cityList = [
    {"id":1,"name":"Vadtal","stateId":1,"isEnable":1},
    {"id":2,"name":"Kandari","stateId":1,"isEnable":1}
  ];

  public myForm: FormGroup;

  constructor(private builder: FormBuilder, private _sanitizer: DomSanitizer) {  }

  ngOnInit() {
    this.myForm = this.builder.group({
      city : new FormControl(''),
    })
  }


  autocompleListFormatter = (data: any) : SafeHtml => {
    let html = `<span>${data.name}</span>`;
    return this._sanitizer.bypassSecurityTrustHtml(html);
  }

  onSubmit(value:any){
    console.log(value);
  }

```
![autocomplete](https://cloud.githubusercontent.com/assets/8941195/21848739/6308d1ca-d828-11e6-99d1-d939ba7aec4c.png)

**Comment by smartHasmukh** [comment]
Hello Guys,
Please help me for fix this issue
@allenhwkim @ndcunningham @Tanato @boban984 @Krisa

**Comment by Tanato** [comment]
You tried to use NgModel instead of FormControl?

HTML
 [(ngModel)]="city"

TS
city: any;

**Comment by smartHasmukh** [comment]
My entire architecture is not support ngModel so please suggest me another way

**Comment by Tanato** [comment]
Can you set up a JSFiddle with this issue?

**Comment by smartHasmukh** [comment]
I have to make it `http://plnkr.co/`. please give me 10 min.

**Comment by smartHasmukh** [comment]
@Tanato  Please check it now - [Plnkr](http://plnkr.co/edit/a3XB9iMaeNvL3KQTr0pq?p=preview)

**Comment by allenhwkim** [comment]
@ndcunningham Can you take a look at this?

**Comment by smartHasmukh** [comment]
Guys have you checked my demo from [Plnkr](http://plnkr.co/edit/a3XB9iMaeNvL3KQTr0pq?p=preview)?

**Comment by ndcunningham** [comment]
Yes https://github.com/ng2-ui/ng2-auto-complete/pull/96

**Comment by smartHasmukh** [comment]
@allenhwkim It does not working. I have tried so please help me how can I do it? I have latest auto complete install but not working

**Comment by smartHasmukh** [comment]
Working fine Thanks @allenhwkim  and @Team
