### ISSUE TITLE
Prefill input

### ISSUE THREAD

**Issue by FlyingKatinka** [ng2-ui/ng2-auto-complete#93]
Hi, 

thanks for the great module. 

I have a question and I'm not sure if I only don't know how to do it or if this feature is not possible yet. I use the autocomplete to fill a value in an object which gets saved to a database. The object can be edited later on. If it get's edited I'd like to prefill the value of the input field with the saved value. Is that possible?

Thanks in advance!

**Comment by flashdave1973** [comment]
in the doc example the input is to `[(ngModel)]="myData"`... Would it not be possible for you to update `myData` from another service and then display that data?

**Comment by allenhwkim** [comment]
@flashdave1973 as @flashdave1973 suggests, use ngModel for that purpose.

**Comment by FlyingKatinka** [comment]
That's it! Thanks for the super fast hint.
