### ISSUE TITLE
Edit - No Match Found - Text

### ISSUE THREAD

**Issue by flashdave1973** [ng2-ui/ng2-auto-complete#95]
Love the project..

I was wondering if it will be possible to edit the `No Results Found` text and allow for callback if selected?

**Comment by allenhwkim** [comment]
There is "No Match Found" for http call. 
https://github.com/ng2-ui/ng2-auto-complete/blob/66776e7f340bd2302de521902e6ef17d77e1c334/src/ng2-auto-complete.component.ts#L38

And the design for 'No Match Found' is only for informational, and not clickable. You can select a blank item though.

**Comment by flashdave1973** [comment]
so hard coded `No Result Found` causes an issue with localization and translations. Also `blank` item is not available when no results found... can we make it available?  and can we submit a string to change the text value of `No Result Found`?

**Comment by allenhwkim** [comment]
You need to specify "blank-option-text" to see blank item.

**blank-option-text**, string, guide text to allow empty value to be selected as in empty value of option tag.

**Comment by allenhwkim** [comment]
@ndcunningham can you change this "No Match Found" to be configurable like 'blank-option-text'?

**Comment by flashdave1973** [comment]
Yessir... I understand how `blank-option-text` works... however it is not an available option when `No Result Found` is displayed, as far as I can tell.

**Comment by allenhwkim** [comment]
So, what you need is to have mousedown available for `No Match Found`?

Before:
```
      <li *ngIf="!isLoading && !filteredList.length">No Match Found</li>
      <li *ngIf="blankOptionText && filteredList.length"
          (mousedown)="selectOne('')"
          class="blank-item">{{blankOptionText}}</li>
```
After:
```
      <li *ngIf="noMatchFoundText && !isLoading && !filteredList.length"
          (mousedown)="selectOne('')
          class="blank-item">{{noMatchFoundText}}</li>
      <li *ngIf="blankOptionText && filteredList.length"
          (mousedown)="selectOne('')"
          class="blank-item">{{blankOptionText}}</li>
```

**Comment by ndcunningham** [comment]
is this a new feat?

**Comment by flashdave1973** [comment]
yessir.. thank you sir

**Comment by allenhwkim** [comment]
@ndcunningham that's a suggested new feature. Not implemented yet.

**Comment by allenhwkim** [comment]
This feature has been implemented closing
