### ISSUE TITLE
min-chars=1 then backspace, shows entire list

### ISSUE THREAD

**Issue by crh225** [ng2-ui/ng2-auto-complete#97]
Hello
Im using the auto complete like
```
<input auto-complete 
  class="form-control"
  [(ngModel)]="selectedColumn" 
  [source]="columnsNotInDv" 
  [min-chars]="1" 
  [max-num-list]="10"
  placeholder="enter column name"
  display-property-name="DisplayName">
```
If I type in something that matches, with one character everything shows fine. Then if I backspace the one character out, it shows the entire list again.

**Comment by allenhwkim** [comment]
fixed, please verify the test

**Comment by crh225** [comment]
@allenhwkim, did you publish it on NPM already?

**Comment by allenhwkim** [comment]
@crh225 I did

**Comment by crh225** [comment]
@allenhwkim, this is not completly fixed

repeat the steps, and you can see a little grey div that appears, but it is empty.

![image](https://cloud.githubusercontent.com/assets/19475195/22308704/acc376d6-e30d-11e6-9a12-f286cfb6a664.png)
